### ISSUE TITLE
Release Checklist

### ISSUE THREAD

**Issue by abschwenker** [bcgov/SIMS#1048]
The following is a list of activities in progress that must be complete before launch

This will be updated daily

# Release Documentation
---
- [ ] PIA Signed #1349
- [ ] STRA Signed #1350
- [ ] IDIM Onboard (BCSC/BCeID) #1351
- [ ] FRCR signed / OCG approval #1319
- [ ] As-built Functional Documentation #1225 
- [ ] As-built technical Documentation
- [ ] DR Plan
- [ ] Backup Plan
- [ ] Fall-Back DR Plan
- [ ] Accessibility (AA standard)

# Production Setup
- [ ] Environment deployment
- [ ] Data load
- [ ] Initial data transition load
- [ ] Integrations

# Testing
---
- [ ] Load Tests
- [ ] Vulnerability Tests
- [ ] Assessment Calculation Tests
- [ ] Regression Testing #1381
- [ ] Integration testing

# Training
---
Each area is required to have training material
- Technical Specifications
- Functional Specifications
- Business process documentation
- [ ] Epic 1.1 #5
- [ ] Epic 1.2 #58
- [ ] Epic 1.3 #59
- [ ] Epic 1.4 #71
- [ ] Epic 2.1 #62
- [ ] Epic 2.2 #265
- [ ] Epic 2.3 #1002
- [ ] Epic 2.4 #690
- [ ] Epic 2.5 #266
- [ ] Epic 2.6 #591
- [ ] Epic 3.1 #229
- [ ] Epic 3.2 #394
- [ ] Epic 3.3 #1009
- [ ] Epic 3.4 #263
- [ ] Epic 3.5 #410
- [ ] Epic 4.1 #841
- [ ] Epic 4.2 #866
- [ ] Epic 4.3 #590
- [ ] Epic 4.4 #865
- [ ] Epic 5.0 #864
- [ ] Epic 6.1 #867
- [ ] Epic 6.2 #267
- [ ] 
Added Integration Contact email addresses when we migrate to PROD#1918
THIS IS A LAUNCH RELEASE TASK.

This is a necessary step. The integration contact email is currently set to internal email addresses as to not inundate Institution contacts with test emails. When we migrate to production, we will need to update the email addresses based on the ones currently assigned for institutions in SFAS.

**Comment by SaurabhA-CGI** [comment]
Other things to consider:

- Testing: UAT, Performance

- Production Deployment checklist. Communication to user groups

- User Guide/Training Material

**Comment by ninosamson** [comment]
Closing as obsolete and replaced by #2693
