### ISSUE TITLE
Update Student Full-time / Part-time Application to include Acceptance Criteria/ Validation

### ISSUE THREAD

**Issue by roopfw** [bcgov/SIMS#147]
- [ ] Update all the applications to reflect acceptance Criteria
- [ ] A student can save a draft application at any time during the application flow.  (#355)
- [ ] Adjust to make it closer to the Figma Design (as possible) 

** Capabilities Include:**
---Application Logic (If 'this answer" then 'that question or pop-up' is provided)
---Search bar (For School, Programs and Offerings)
---Pop-Up Warnings
---Free Text Short Description
---Free Text Long Description
---Free Text Numbers
---Document Uploader -Drag and Drop documentation or document upload (PDF and image files (jpg,png,bmp)
---Standard Calendar Dates Selection
---Save this information to the Students Profile
---Call information from other parts of the Student Account (e.g. Student Profile Informatoin)
---Call information from Intitution Accounts (e.g. School, Program and Offering Information)
---Expand and Collaps Text to fit page
---Edit Information
---Save Information
---Each page has an option to go to the Next or Previous Page or both.

** Select Your Program**
- [x] Provide the text "Please give us some more information about your education plans such as courses or programs you will be taking"
- [x]  "The school I will be attending" _(Provide a search bar in a "Search for your school bar" and a radio button for "My School Isn't listed" (In the search bar present only  Institutions Accounts whose Designation Status = Approved) (If the user selects "My School isn't listed, provide the following pop-up text, "Your Institution may not be Designated by StudentAid BC. If your school is not found on this list, it means that the institution you would like to attend is not designated. Please contact your institution so that they can pursue Designation. If your school is not designated you are not able to complete your application at this time"__

**Program Selection**
- [x] "Select the program you will be attending" _(Provide a search bar to "search for your program and a radio button for "My program isn't listed." The search bar presents only approved education programs for the above-selected designated institution._
 - [x] If the user selects " My Program isn't listed" Provide the section: ' _Please provide additional information about your program" and provide the text "Information about how this will trigger a program information request from the institution"_ 
 - [x] Program Name _(Free Text " Enter your program name")_
 - [x] Program Description _(Free Text " Enter a short description)_
 - [x] Start Date _(Standard Calendar)__ 
 - [x] End Date _(Standard Calendar)__ _(The Dates must be a minimum of 42 days and a maximum of 365 days- if longer or shorter provide a red error "Invalid Study Period, Dates must be between 42 and 365 days")_ 
- [x] "Select the Program Offering you will be attending:" __"  and a radio button for " My program offering is not listed" In the search bar present only approved offerings associated with the above-selected education program.
 - [x] If the user selects " My Program Offering isn't listed" Provide the section: ' _Please provide additional information about your Program Offering" and provide the text "Information about how this will trigger a program information request from the institution"_ 
 - [x] Start Date _(Standard Calendar)__ 
 - [ ] End Date _(Standard Calendar)__ _(The Dates must be a minimum of 42 days and a maximum of 365 days- if longer or shorter provide a red error "Invalid Study Period, Dates must be between 42 and 365 days")_ 
- [x] The student must have the ability to go to the next section in the application.

**Personal Information**
 - [x] Provide the text, "Your StudentAid BC Profile Information". "This information was provided by you when you first signed in to your account as well as shared by your BC Services Card login. If this information is out of date click here _(hyperlink to profile)_  to visit your profile to find out how you can update it. 
- [x] Display Profile Information: Given Names, Last Name, Email Address, Date of Birth, Gender, Home Address, Phone Number. _(This information is from the student profile)_ 
- [x] Check box for the user. " I confirm my StudentAid BC Profile information shown is correct"
- [x] What is your citizenship status? (_Provide the following options: Canadian Citizen, Protected Person, Permanent Resident)_ 
     - [ ] If the user selects 'Protected Person or Permanent Resident, ' provide the following pop-up. "Based on your answer, StudentAid BC requires that you to upload proof of your citizenship status in order to apply for student aid funding. Please upload a scanned copy of documentation that confirms your selection below." _(Drag and Drop documentation or document upload (PDF and image files (jpg,png,bmp)_ _(Required)_
- [x] Are you a Resident of BC?  _(Yes / No)_ 
   - [x] If the User Selects 'No' provide the following pop-up. "Please provide the additional information, " You indicated that you are not a BC Resident", If any of the following circumstances apply, you may still be eligible for StudentAid BC funding, " Which of the following best describes your situation?" __Present the 5 options listed in the Figma.
   - [x] If the user selects 'other' provide a free text long box "Please explain your situation:" and provide a section to "upload supporting documentation (optional)")
- [x]  Do you identify as an Indigenous person? (_Yes/ No)_
     - [x] If ' Yes' is selected provide the pop-up "Aboriginal Heritage" I am _(provide the options: First Nations, Metis, Inuit)_
- [x] Were you ever a youth in continuing care or custody of a director of child welfare in BC (ward of the court – this means the provincial government is/was your legal guardian)?  _(Yes / No)_
    - [x] If ' Yes' is selected provide the pop-up, "Info about YEAF and TWP to be displayed" 
- [x] When did / will you graduate or leave high school? _(standard calendar)_
- [x] "Employment Information," "Will you be working a full-time job of 32 hours per week for more than half of your study period? _( Yes or No)_
     - [x] If ' Yes' is selected provide the following pop-up, "StudentAid BC Requirement", "StudentAid BC requires applicants not to work a full-time of more than 32 hours per week for at least half of their study period."
- [x] "In the time since you left high school to your first day of classes, have you spent two periods of 12 consecutive months each, in the full-time labor force?" _(Yes / No)_
- [x] Provide the following text, "Share Information with a Trusted Contact," "Do you want to allow another person to be able to contact StudentAid BC and inquire about the status of your application or provide additional information on your behalf? (A parent/guardian for example.)"
- [x] "Do you want to allow a trusted contact to interact with StudentAid BC on your behalf?" _(Yes / No)_
    - [x] If 'Yes' is selected provided the Trusted Contact 1 Pop up. and provide the following Fields'
         - [ ] First Name, Last Name
 - [x] How long do you want to give this person access to your StudentAid BC Account? _Provide the following options:_ 
       - [ ] "Until the end of the study period of the application"
       - [ ] 'Until I remove them' 
       - [ ] If 'Specific Date' is selected provide the following: "Select the date you would like this person access to your StudentAidBC Account to Expire" _(Standard Calendar- must be in the future)_
- [x] Provide an option to Add another Trusted Contact _(pop up the same fields)_ _(Max of 2 Trusted Contacts)_
- [x] If A trusted Contact was provided (_Provide a check box "I agree to share my application information with the trusted contact(s) entered above)_
- [x] The user must have the ability to go back to the previous section in the application or continue to the next section in the application.

**Family Information**
- [x] On my first day of class, I'll be (_Provide the following options, Single, Separated /divorced/ widowed, Married / Common Law)_
    - [x] If the Student selects "married/common-law" _Provide a Select Date box (Standard Calendar)  "Date of marriage or date of start of living together in a marriage-like relationship"_
- [x] Do you have any eligible dependants? (_Yes/ No)_
     - [x]  If Yes is selected, _provide the following pop-up- Dependant 1. "Add Dependants" "We use this information to ensure that we take into account your... (text TBD)_ 
      - [x] Full Name, _(Free Text)_  Date of Birth
      - [x] "Will this dependant be attending high school or full-time post-secondary school at the start of your classes?" ( Yes/ No)"
      - [x] "Did you claim this dependant on your 20xx _(Call previous tax year)_ Income Tax Return due to a disability?" (Yes/No)
      - [  ] Provide an Upload Supporting Documentation Feild _if Dependant is 12 or older and with a disability on income tax_
- [x] The Student can add additional Dependants, 2,3,....) _(Same pop-up box)_
- [x] The Student can remove dependants
- [x] 'Do you have any dependents that you support financially but do not have sole custody of?" (Yes/ No) 
     - [x] If "Yes' is selected,  provide an Upload Supporting Documentation box with the text, "Based on your answer StudentAid BC requires that you upload supporting documentation to support your answer…" 
- [x] The user must have the ability to go back to the previous section in the application or continue to the next section in the application.

** Partner Information** (This section is displayed only if the student selected 'married/common law' on the previous page.
- [x] Is your partner a Canadian Citizen and have a valid SIN number (Yes/ No)
    - [x]  If 'Yes' is selected, _provide a pop up "Please be advised that your partner will need to sign in and provide additional information.... (see figma for more text)_
    - [x]  If, 'No' is selected, _provided a pop-up, "This could delay your application"...  (See Figma for more text)_
- [x] Partner Income, "What was your partner’s income (as shown on line 15000 of the previous year’s Canada Revenue Agency tax return)? If they didn’t file taxes, enter total income from all sources in and outside of Canada." _(Provide a free text $ field)_
- [x] "Will your partner be employed full-time or part-time during your study period" (Yes/No)
- [x] "Will your partner be at home caring for eligible dependent children on a full-time basis during your entire study period?" _(Yes/No)_ 
- [x] "Will your partner be living with you during your study period?" _(Yes/No)__
- [x] "Will your partner be a full-time post-secondary student for some or all of your study period?  _(Yes/No)__
 - [x] If "Yes' is selected provide the following question, "If your partner will be a full-time student, how many weeks of your study period will they also be in studies?" _and free text ' Enter Weeks' Feild- ( _Must be Equal to or less than Student Applicants study period)_
- [x] "Will your partner receive income assistance/social assistance (welfare) and/or BC income assistance for persons with disabilities during your study period?" ( Yes/ No)
      - [ ] If 'yes' is selected,"Provide the total income assistance/social assistance (welfare) and/or BC income assistance for persons with disabilities that your partner will be receiving during your study period." _(Free Text Dollars Feild)_
- [x] "Will your partner be in receipt of Employment Insurance benefits during your study period?" _(Yes/No)_
    - [x] If 'Yes' "Enter an estimated amount that your partner will receive during your study period. _(Free Text Numbers Feild)_
- [x] "Will your partner be in receipt of federal or provincial permanent disability benefits during your study period?" _(Yes/ No)_ 
    - [x] If 'Yes' "Enter an estimated amount that your partner will receive during your study period. _(Free Text Numbers Feild)_
- [x] "Will your partner be paying a Canada Student Loan and/or a provincial student loan regular scheduled payments during your study period?" _(Yes/No)_
     - [x] If 'yes" Is selected, provide the text, "Enter amount that your partner will pay during your study period." and a _(Free Text Dollars Feild)_
- [x] "Will your partner be paying for child support and/or spousal support during your study period?" _(Yes/ No)_ 
     - [x] If 'Yes' is selected, provide the following text, "Enter amount that your partner will pay during your study period" and a _(Free Text Dollars Feild)_ 
- [x] "During your study period, will your partner be taking care of eligible dependents?" _(_Yes/ No)__ 
- [x] The student must have the ability to go back to the previous section in the application or continue to the next section in the application.

**Parental Information** (Provide this section only if the student has identified themselves as a dependant- shown IF Intensity = graduated less than four years before their study start date + marital status is single OR no dependants, Modified Independent status = No or blank)
- [x] Are both parents Canadian Citizens and have a valid SIN numbers
     - [x] Both of my parents have passed away and I have no legal guardian
     - [x] I am estranged from both my parents
     - [x] If, 'No' _(TBD- Estimates on both parents pages)_ 
     - [x] If 'Yes', provide the following question. "Is your parent(s)/step-parent/sponsor/legal guardian a resident of BC? Provide the following radio button options_( 'Yes'/ 'No')_
    - [x] If 'Yes' is selected, _Provide the following pop-up, "Please be advised that your parent(s) will need to sign in and provide additional information"... continue text from Figma)_
    - [x] If ' No" is selected, Provide the following questions:  _(This will be provided from the Parents once built)_
    - [x]  If the Student Selected, "No (Not a BC Resident)" also provide the following pop up, "Please Provide Supporting Information," "You indicated that your parent(s) are not B.C. Residents. If any of the following circumstances apply, you may still be eligible for StudentAid BC funding" Which of the following best describes your situation" (Provide the 8 options listed in Figma.
         - [x] If the student selects "none of the above _ provides,:  "Please explain your situation" (long text `box)`_
   - [x] If the Student Selected " I am estranged from both my parents." in the first question, _Provide the pop- up, "Please Provide Supporting Information"  "Help Text TBD", "Please explain your being estranged": _(Long Text Box)___
        - [x] "Upload Supporting Documents (Optional)" _(Document Uploader)_
  - [x] If the Student Selected "No"
         - [ ] Please Provide an estimate of your parents income
- [x] Your Siblings and other Parent Dependents _(Header)_ _(Not required if the parent selects Estranged)_ 
- [x] Provide the Text, " We use this information to ensure that we take into account your parent(s) responsibility to other dependants…"
- [x] Do your parents have dependents other than yourself? _(Yes/ No)_
     - [x] If ' Yes' is selected _provide the following pop up questions._
     - [x] Dependent 1 (_Header)_
           - [ ] Age at start of your study period. _(Free Text Numbers Feild)_
           - [ ] Will this dependant be attending high school or full-time post-secondary school at the start of your study period? _(Yes/ No)_
            - [ ] Did your parent(s) claim this dependant on their 20xx _(Call previous tax year)_ Income Tax Return due to a disability? _(Yes/ No)_
- [x] Given the Student needs to provide more Parent Dependents, _Provide an "Add Another Dependent" button, (They become Dependent 2, 3..._  Provide the same pop-up Questions as Dependent 1._ 
- [x] Given they need to remove a parent dependent, then they can select "Remove Dependent"
- [x] The Student must have the ability to go back to the previous section in the application or continue to the next section in the application.

**Financial Information**
**Show the following section for BOTH DEPENDENT AND INDEPENDENT Students**
- [x]  20xx (previous Year) Tax Return Income. _Provide text from Figma._ My total income in 20xx was (_Free text numbers box- no decimals- no cents)_
   - [x] Canada Revenue Agency Consent (Provide text from Figma.) For Page Size, Provide the Option to 'Read More' or 'Read less' Text
    - [x] " I give the Canadian Revenue Agency consent to verify the data I have provided in my application" _(Check box)_
- [x] Financial Exemption- Provide the text, "If you have had, or anticipate having a significant decrease in income for 2021, you may request to be assessed using this year's estimated income."
    - [x] Do you want to be assessed with this year's estimated income? _(Yes/ No)_ 
- [x] If 'Yes' is selected provide the following: "Please Provide Supporting Information" _Provide Text from Figma_ My Total Current year income is: _Free text number box)_
     - [x] Select the reason for your significant decrease in income. Provide the following options, "COVID- 19, Medical Illness or injury, Family emergency (e.g., death or injury), Natural Disaster, Layoff, strike, lockout or other reduction in earnings beyond the family’s control, Other Exceptional Circumstance"
         -[ ] If "Other Exceptional Circumstance" was selected, Provide, "Please explain your exceptional circumstance" _(Long-form text box)_, 
         - [x] "Upload Supporting Documenation (optional)" _(Document Uploader)_
- [x] " You can submit an exemption request if you had exceptional expenses that created financial hardship that affected your ability to start or continue your studies."  Do you want to submit an exemption request for exceptional expenses?" _(Yes/ No)_
  - [x] If "Yes' is selected, provide, "Upload Supporting Documents of Your Exemption Request" an_d additional text from Figma._ _(Document Uploader)_
 - [x] "Other Financial Supports", "Explanation of Text- tbd", "Will you have Merit-based scholarships or need-based bursaries, including provincial government scholarships received during your study period?" _(Yes / No)_
      - [x] If ' Yes' Selected Provide, "Value." _(Free Text Numbers Box including cents)_ 
- [x] Will you receive voluntary contributions from parent(s)/step-parent/sponsor/legal guardian: _(Yes/ No)_
     - [x]  If 'Yes' is selected, provide, ""Value." _(Free Text Numbers Box including cents)_ 
- [x] "Will you have Government funding (e.g., E.I> training allowance, social assistance payment intended to cover education-related costs) during your study period" _(Yes/ No)_
 - [x] If 'Yes' is selected, provide, ""Value." _(Free Text Numbers Box including cents)_ 
- [x] "Will you have non-government (private sector) funding (e.g., employer) during your study period" _(Yes/ No)_
 - [x] If 'Yes' is selected, provide, ""Value." _(Free Text Numbers Box including cents)_ 
- [x] "Will you have BC income assistance for persons with disabilities that you will be receiving under the Employment and Assistance for Persons with Disabilities Act during your study period" _(Yes/No)_
      - [ ]  If 'Yes' is selected, provide, ""Value." _(Free Text Numbers Box including cents)_ 
- [x] "Transportation"- "If you must relocate to a different city to attend school,  do you want to provide a cost to be considered? _Yes/ No__
       - [ ] If yes provide " Value"  _(Free Text Numbers Box including cents)_
- [x] " Additional Transportation" " You may be eligible for an additional transportation allowance if there is no/limited local public transit where you live, or if you are required due to special circumstances. Do you want to be assessed for additional transportation costs" _Yes/ No_
    - [x]  If 'Yes' is selected, provide, the question, "Which of the following best describes your situation?" Provide the following options, "There is no/limited local public transit where you live," "The travel is required due to special circumstances (e.g., work schedule, family transportation responsibilities, or a requirement to live a significant distance from your post-secondary institution)", "Additional transportation for a clinical or practicum placement is required.", " Other" 
     - [x] If 'Other' Is selected, provide the following, "Please explain your situation:" _(Long Text Box)_
           - [ ] "Upload supporting documents (optional)": _(Document Uploader)_
           - [ ] "Please estimate your weekly transportation costs." _( Free Text Numbers Box)_ 
     - [x] If any other option is selected,  Provide,  "Please estimate your weekly transportation costs". _( Free Text Numbers Box)_ 
            - [ ] "Upload supporting documents (optional)": _(Document Uploader)_
- [x] - [ ] The Student must have the ability to go back to the previous section in the application or continue to the next section in the application. 

**Show the following questions to INDEPENDENT students only. An Independent student must have graduated more than four years before their study start date + marital status is not single or they have at least one dependant.**

- [x] Dependant Care Cost _(shown if Dependants = Yes and at least one of them is 11 or dependents who are 12 years and up and have PD.)_
- [x] Will you have a child age 11 years or under in daycare? (_yes/ no)_
    - [x] If ' Yes' provide, "Daycare costs that you incur for your child(ren) age 11 years or under:" _(Free text Numbers Box with cents)_
 - [x] Will you have unsubsidized day-care costs during class hours for disabled/ infirmed dependents 12 years of age or older? _Yes/ No_
      - [x] If Yes provide, "Total unsubsidized day-care costs during class hours for the proposed study period for disabled/infirmed dependents 12 years of age and older": _(shown if Dependants = Yes and at least one of them is 12 years or older due to a disability or illness)_ _(Free text Numbers Box with cents)_
  - [x]  "Will you be paying child support and/ or spousal support during your study period?"  _(Yes / No)_
         - [ ] If, 'Yes" is selected, Provide, " Amount paid during study period." _(Free Text Numbers Box)_

**Show the following only for DEPENDENT Students**
- [x] Living Situation- "Will you be living in a home paid for by your parent(s)/step-parent/sponsor/legal guardian during your study period?" _(Yes/No)_
     - [x] If, 'Yes" is selected provide, "Will you be paying room and board (rent) to your parent(s)/step-parent/sponsor/legal guardian? _(Yes / No)_
          - [x]  If 'Yes' is selected, provide, "Please add Supporting Information" "If you  are living at home and need to pay room and board, additional expenses may be considered as part of your assessment", "Which of the following best describes your parent(s)/step-parent/sponsor/legal guardian situation?", Provide the following options: "Receiving income assistance or permanent disability benefits", "Receiving Canada Pension and/or old age supplement, with no other source of income or support", "Earning low income, and/or unemployed due to layoff, strike or lockout", and "Other."
        - [x] If 'Other" is selected provide, " Please explain your situation" _(Long Text Box)_
        - [x] "Upload supporting documents (optional)" _(Document Uploader)_

     
**Declarations**
- [x] "Declarations", "StudentAID BC Consent" _Provide Figma Text... (Read more / Read Less option to fit the screen)_
- [x] "I give StudentAid BC consent to verify the data I have provided in my application" _(Check Box)_
- [x] The Student must have the ability to go back to the previous section in the application...

- [ ] The Student has the option to 'Save' or 'Submit' an application.
    - [ ] If the selects 'Save'... The student can log in at a later date to complete their application. 
   - [ ] If the selects 'Submit'... The student is directed to the "Application Complete Page", "Thank You", "Your application has been submitted. You will receive a notification when the application is processed" (#534)
    - [ ] The Student has the option to select "Back Home" Which takes them to the Student Home (Dashboard) Page. 

** Task**
- [ ] Fetch list of all institution locations when a student selects institution dropdown
- [ ] Fetch list of all Active programs
- [ ] Fetch list of all Offerings 

https://www.figma.com/file/VykmBDwobGoGvK9M5wgOvN/StudentAid-BC-App-Design-System-(WIP!!)---FreshWorks-Studios?node-id=642%3A2733
