### ISSUE TITLE
Implement Banners for Enrolment stage on Student Application Tracker

### ISSUE THREAD

**Issue by JasonCTang** [bcgov/SIMS#1665]
### Context
Enhancements to display relevant information for the **Enrolment** stage of the student application tracker. These may need to be broken up into smaller tickets.
______________________
### Reference mockups
https://www.figma.com/file/9Om2tzLAVEoMQrjmrH4fhu/MOD-SIMS?node-id=7809%3A108528&t=WNRHHCnCKfJXwzsH-0
______________________
#### Enrolment stage 
- [x] If COE, display "waiting" banner and orange bar
- [x] If COE DECLINED, display red banner and red bar (w/ alert icon)
![image.png](https://images.zenhubusercontent.com/6047d6ac906f4ec904f7286c/69a26848-1db4-447c-a7ad-ee655de52cc9)
- [x] If 2 COE, display 2 "waiting" banners and orange bar
- [x] In "Application actions" menu, replace "Edit applications" with "Request a change" link

______________________

#### Completed (for original assessments) 
**HAPPY PATH 😸**
- [x] If COE confirmed, display green banner and green bar (w/ check icon)
- [x] If Payment SENT, display green banner and green bar (w/ check icon)
- [x] If 1 of 2 COE confirmed, display 1 green banner, green bar (w/ check icon), 3 waiting banners
- [x] If 1 of 2 Payment SENT, display 2 green banners, green bar (w/ check icon), 2 waiting banners
- [x] If 2 of 2 COE confirmed, display 3 green banners, green bar (w/ check icon), 1 waiting banner
- [x] If 2 of 2 Payment SENT, display 4 green banners, green bar (w/ check icon)
- [x] NICE TO HAVE (background green highlight of last card) - DEV investigate what we have done for other stages
![image.png](https://images.zenhubusercontent.com/6047d6ac906f4ec904f7286c/bea8dc21-88de-481b-ba91-0938f0ac4f1b)

 **UNHAPPY PATH 😿**

- [x] If 1 of 2 COE (DECLINED), display red banner and red bar (in enrolment)
- [x] If 2 of 2 COE (DECLINED), display red bar (in completed), 2 green banners, 1 red banner, and hide waiting banner
![image.png](https://images.zenhubusercontent.com/6047d6ac906f4ec904f7286c/e4338e66-50ec-4e59-98d0-5422f22c34dd)

______________________

#### Completed (for reassessments)
 **UNHAPPY PATH 😿**
Follow the same "pattern" as above for original assessment (e.g. waiting, success, decline banners)

______________________

#### Completed (for reassessments) - new ticket
- appeal, scholastic standing

_Scenario: Application was in completed stage, but then Student requests a change and triggers a reassessment_
- [ ] If student submits change request, display orange bar (w/ warning icon), orange banner, waiting banner
- [ ] If student change request APPROVED, display green bar bar (w/ check icon), green banner, waiting banner
- [ ] If student change request DENIED, display red bar (w/ alert icon), red banner, hide waiting banner
 
_Scenario: Application was in completed stage, but then School requests to change offering dates_
- [ ] If offering request is approved by the ministry, trigger NEW ASSESSMENT, display a green banner, green bar (w/ check icon), waiting banner
- [ ] If request is IN PROGRESS or DECLINED, no UI is required to display

_Scenario: Application was in completed stage, but school reports scholastic standing_
- [ ] If school reports student (switched FT/PT, withdrawal, or early completion) - trigger NEW ASSESSMENT, display a green banner, green bar (w/ check icon), waiting banner 
- [ ] If school reports student (unsuccessful completion) - NO reassessment required, display red banner, red bar (w/ alert icon), hide waiting banner

______________________

#### UNKNOWNS
 ?? - Can we have 1 COE approved and 1 COE declined (Need to consult with business)
 ?? - More than 2 COEs (Need to consult with business)

**Comment by dheepak-aot** [comment]
Application progress bar scenarios:

---------------Enrolment---------------

Application in enrolment status with 1 enrolment waiting

Application in enrolment status with 2 enrolements waiting

Application in enrolment status with first enrolment declined

Application in cancelled status: 2022000161

-------------Completed---------------------------

Application with 1 enrolment waiting for ecert to be sent

Application with 1 enrolment and e-cert sent 

Application with 2 enrolments and first enrolment confirmed

Application with 2 enrolments and first enrolment confirmed and first payment sent

Application with 2 enrolments and both the enrolments confirmed and first payment sent

Application with 2 enrolment and both the enrolment confirmed and botht the payment sent

Application with 2 enrolment and second enrolment declined
