### ISSUE TITLE
Implement Banners for Completed stage on Student Application Tracker

### ISSUE THREAD

**Issue by JasonCTang** [bcgov/SIMS#1683]
Implement banners for the completed stage on Student Application Tracker.

### Scenarios

- Student request change (generates an assessment only if approved).
- Institution reports scholastic standing
    - Switch FT/PT
    - Withdrawal
    - Unsuccessful completion (does create a reassessment)
    - Early completion
- Institution changes the offering.

### Reference mockups

https://www.figma.com/file/9Om2tzLAVEoMQrjmrH4fhu/MOD-SIMS?node-id=7809%3A108528&t=WNRHHCnCKfJXwzsH-0

#### Completed (for reassessments) 
- Requests a change
- Scholastic standing
- Offering changed requested by the institution

_Scenario: the application was in the completed stage, but then the Student requests a change and triggers a reassessment._  The request for change DOES NOT generate an assessment until it is approved.  If it is declined, it WILL NOT generate an assessment.
- [ ] If a student submits a change request, display an orange bar (with a warning icon), an orange banner, and a waiting banner icon.  
- [ ] If the student change request is APPROVED, display a green bar (with a check icon), green banner, and check banner icon.
- [ ] If the student change request is DENIED, display a green bar (with no alert icon), error banner, and error banner icon.
 
_Scenario: the application was in the completed stage, but the school reports scholastic standing._
- [ ] If a school reports a student (switched FT/PT, withdrawal, or early completion), a new assessment will be triggered, display a green banner, green bar (with check icon), waiting banner icon.
- [ ] If a school reports a student (unsuccessful completion) - NO reassessment required, display red banner, red bar (with alert icon), with error banner icon. _This scenario is not clear at this moment as there are no requirements yet for how to properly handle the reassessments for scholastic standing, which also includes what happens after an "unsuccessful completion" is reported._

_Scenario: the application was in the completed stage, but then the school requests to change offering dates._
- [ ] If the offering request is approved by the ministry, trigger NEW ASSESSMENT, display a green banner, green bar (with check icon), check banner icon.
- [ ] If the request is IN PROGRESS or DECLINED, no UI is required to display
