### ISSUE TITLE
Student Authenticates with BC Services Card

### ISSUE THREAD

**Issue by mzmichellesmith** [bcgov/SIMS#17]
As a  Student, I want to authenticate my identity with Student Aid by using  my standardized Government Services ID so that I don’t have to enter the same information every time I access government services

**Additional Context**
- Only students who are residents of BC qualify for Financial Aid and therefore should have a Services Card.
-SABC requires that a student's identification is validated against government-issued ID and authentication. The current secure method for this BC Services Card.
-The BC Services Card provides access to other government services for B.C. residents.  With just one card, they can access many different government services.
All attributes from BCSC are read-only and user must go to ICBC to change. After doing that the information will show up in the OpenIDConnect payload. 
- It is the BC government's secure way to prove who a citizen is online.
-If the student does not have a BC Services card or they are having issues with the BC Services Card Site, the student will need to contact the Service BC/ ICBC to get one.
Information from BC Service Card will be read-only on the SABC Account.
The information from Services Card includes Given Names, Last Name, , Date of Birth, Email, and Gender as read-only. 
When BC Services card information is updated, then the information will be updated on the SABC account).- Another User Story

**Acceptance Criteria**
- [x] Given (The student), has successfully authenticated their BCSC login, Then the BC Services Card site will redirect the Student back to the SABC site to complete their SABC Profile.
- [x] Given the Student does not have a BC Services Card, Then (the student will be directed to the BC Services Card site to activate their services card and their SABC account record is not created until their BC Services Card authenticated.
- [x] Given The Student's  BC Services card authentication is not successful, then (the student will remain on the BCSC log-on site until it is authenticated.

**Task List**
------------
- [x] Verify BCSC Identity Provider
- [x] Create Public client for local and remote env in Keycloak
- [x] Create (Reuse/Review) and test Client scope with all required information
- [x] Create Client Role and assign it as default role
