### ISSUE TITLE
UIUX - Modifying the student tracker cards to display more details about exceptions/restrictions

### ISSUE THREAD

**Issue by JasonCTang** [bcgov/SIMS#1783]
**As a** *Student* **I want** *to have more information about any actions required on my application* **So That** *I can action these items and receive funding*

**Additional Context**
Additional tracker cards to be added for any situations that will prevent/delay disbursement of funds to students and possibly require their action.

**Acceptance Criteria**
- [ ] Tracker Card for: MSFAA not signed
- [ ] Tracker Card for: MSFAA verification issue
- [ ] Tracker Card for: PD Status is not verified and is applied for on application
- [ ] Tracker Card for: PD Status is not verified and is applied for on application AND within 2 weeks of study end date
- [ ] Given (Context), When (action carried out), Then (expected outcome)

**Comment by CarlyCotton** [comment]
## Notify Student About Blocked Disbursements (Email and Tracker Card) #2536
**Description of Task**
Configure new email sent to students anytime a disbursement is being withheld for any reason
Add new application status tracker card explaining reason for blocked disbursements

##Incorporate Additional Cards on Student Application Tracker #2377
**Description of Task**
Add new cards to appear below the student's application status tracker which communicate any blockers to a student's disbursement.
