### ISSUE TITLE
Request an Offering Change - Students Application Tracker

### ISSUE THREAD

**Issue by andrewsignori-aot** [bcgov/SIMS#1977]
## Figma

- **Mockups (Student)**
https://www.figma.com/file/9Om2tzLAVEoMQrjmrH4fhu/MOD-SIMS?type=design&node-id=11899-182182&t=4YxLxpDo4EjFolAN-0

- **Mockups (Workflow - end to end journey)**
https://www.figma.com/file/9Om2tzLAVEoMQrjmrH4fhu/MOD-SIMS?type=design&node-id=11899-182182&t=cHzOlNb6QSEFAbFH-0

## Scenario

- Institution submits form with offering change
- Student receives an email notification
- **Student login and is prompted to "allow" or "decline" the change (on the app tracker)**

## Acceptance Criteria
- [ ] Add an email notification for the scenario: offering change request In progress with student. As per the discussion with @JasonCTang, we will be sticking to this template (attached below) for the initial email to the student when the institution first submits the request to change an application offering for said student. A separate single template will be used to notify the student regarding the actions that the Ministry takes on the request later in the process.
- [ ] On app tracker, in completed status, add a warning card with button "Review changes" when status is in progress with student. 
- [ ] If student approves, display the card showing the request is pending SABC approval.
- [ ] If student declines, display student declines card.
- [ ] If ministry approves, display ministry approved card.
- [ ] If ministry declined, display ministry declined card.
- [ ] All of the same logic from student appeal to display the declined cards.  The status are based on the most recent submitted request for change. 
- [ ] Display request in "assessment" table - following same logic as other scenarios.
- [ ] Display button "Review changes" that goes to view request page.
- [ ] As per discussion with @JasonCTang, when there is atleast one of the following (appeal, exception, offering request or offering change request) in progress with the student application, we are showing amber color in the application tracker. 
- [ ] e2e test.
- [ ]

## Email content

See draft folder in "notify" for content.

![image.png](https://images.zenhubusercontent.com/6047d6ac906f4ec904f7286c/3cf9bf56-903c-4959-85d5-f6d482bd367b)

## Related tickets
- #1953 - DB Migrations and List
- #1954 - Institution submit/View UI
- #1977 - Student application tracker _(this one)_
- #1978 - Student views request
- #1979 - Ministry View Pending Offerings
- #1980 - Ministry View Request
- #1981 - Ministry "Request a change" approve/deny create/view assessment

**Comment by dheepak-aot** [comment]
DEV Discussion on endpoint and with auth
![image.png](https://images.zenhubusercontent.com/60e72aa247c95cd873ed8ce1/9aeac05a-5c04-48d7-bb83-7e868612b383)
