### ISSUE TITLE
Missing Tech Activities

### ISSUE THREAD

**Issue by andrewsignori-aot** [bcgov/SIMS#2155]
Collection of items to be discussed with the potential to generate new tickets for the SIMS Team or Ministry.

- [x] API data load testing. #2426
  - Form.io data load/subission. Use the Student Application to test the amount of submission that the form.io server can handle. As a suggestion, we can have a Student Application payload sample submitted multiple times directly to the form.io server and check how the form.io server handles the requests till it stops.
  - Camunda submission capacity trying to establish the workers capacity to handle the requests.
    - Check the performance by increasing the number of PODs.
    - Check if there is the best way to configure workers `maxJobsToActivate`.
- [x] DB data load testing. #2347
- [x] DB automated maintenance and DB-related topis. #2347
  - Indexes defrag/recreation due to fragmentation
  - Possible slow queries and missing indexes
  - Overall DBA support outside the SIMS Team.
- [x] Queue-consumers #2425
  - Check if all consumers are independent to ensure if the same job ends up being processed by two consumers (due to some error) it will still be consistently executed (similar to Camunda workers).
- [x] Loading status on Vue pages and overall loading information. #2426
  - Global solution to handle individual "API calls" where the template with loaded data can be displayed only when data was returned from the remote call.
  - Ensure that every "API or remote call" will have an error handling associated.
- [x] Global error handling on Vue application adding the UI/UX screens from Figma. #2427
  - We already have Figma UI for many page errors and more.
- [x] Camunda retry intervals are not currently defined to final PROD values. Some of them are too short and should be increased to at least a few hours. Need to review case by case.
- [x] Mainly for Students but desirable for all applications, create a page to explain a maintenance time or "System not available". #2429
  - Space to add urgent messages to communicate to the users about some important fact, like urgent maintenance to happen during a window where the system will not be accessible.
 
 - [x] Set and handle the coverage expectation on E2E tests before going prod #2432
 - [x] Improvements on workflow E2E test #2432

**Comment by michesmith** [comment]
Closing this ticket. New Tickets have been created- Ticket numbers inline
