### ISSUE TITLE
Student application tracker adjustments for new assessment trigger type

### ISSUE THREAD

**Issue by dheepak-aot** [bcgov/SIMS#2673]
**User Story**
As a _student_ who has more than one application in a program year (FT and/or PT) my assessment for App 2 may be waiting on App 1 and App 2 may be reassessed due to App 1. In both cases, I want to know what the status of my application is.

**Acceptance Criteria**
- [x] Add waiting tracker card when application is waiting on a related one before assessment:
_**Waiting for other applications in the program year**
There are other applications for this program year that may affect your assessment. Once any earlier applications have been assessed, this application will move to the assessment stage._
- [x] Add tracker card applications who have been reassessed due to a change in a related application for all statuses:
- [x] Completed
- [x] Enrolment
- [x] Assessment
_**You have a new assessment due to another application**
Application NUMBER in this program year had a change in assessment and due to limits within the program year, this application my have been affected. Please review the updated assessment._

**Technical**
- [x] Add a verification check if the in-progress application is waiting for another application to be processed. In-progress details cards are retrieved using the API method [getInProgressApplicationDetails](https://github.com/bcgov/SIMS/blob/46c9bfa3d7c399417bdb4f413251baa3e48d3a72/sources/packages/backend/apps/api/src/route-controllers/application/application.students.controller.ts#L539).
- [x] Use the method [getOutstandingAssessmentsForStudentInSequence](https://github.com/bcgov/SIMS/blob/main/sources/packages/backend/apps/workers/src/controllers/assessment/assessment.controller.ts#L378) to check if the application current assessment id is different than the one returned.
- [x] Adjust the cards displayed based on trigger type to consider the new trigger type `Related application changed`. This card is not displayed for the `Assessment` and `Enrolment` statuses right now and needs to be added. API needs to return the trigger type if not yet returning to determine if the card should be displayed or not. Completed status endpoint already contains it.
- [x] The card should be displayed at the top of all other cards for `Assessment` and `Enrolment`. For `Completed` it should be alongside the other reassessment-related ones.
- [x] Create E2E tests and adjust the existing ones for the modified endpoints.

**Describe the task**
New trackers and content are needed to notify the student when sequential/program year limit reassessments have occurred or are blocking applications.
<img width="761" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBOWM3QXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--a0024bfd6b954b6cd5bf205c08c6be56b5bd4130/image.png" alt="image.png" />
<img width="945" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBOVk3QXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--36931f5c156ec461371c4959123418b9aeb0b8f9/image.png" alt="image.png" />

**Comment by HRAGANBC** [comment]
@dheepak-aot Can you explain a little about what you're looking for here? Are you looking for what messages to display on a student's Application Status Tracker cards when their assessment gets automatically re-assessed because of the Sequential Reassessment feature?

**Comment by CarlyCotton** [comment]
@HRAGANBC This has to do with new notifications for the sequential reassessment. I've done some quick ones in FIGMA that address the two situations in which an assessment might be affected and a student would need to be notified. Open to content suggestions!

<img width="761" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBd1lnQXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--920885a7908389ecc64008f32939a163ab21ece4/image.png" alt="image.png" />

<img width="945" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBeUFnQXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--4b95b6598803418fbaa76d44342dc519c82ccda0/image.png" alt="image.png" />
