### ISSUE TITLE
PT Release Technical Checklist - PROD Readiness

### ISSUE THREAD

**Issue by ninosamson** [bcgov/SIMS#2693]
The following are required to enable PT release for students in PROD environments. Goal is to have everything enabled well before launch. Launch day would simply be to enable configuration for BCSC users. 

External Integrations: 
- [ ] SFTP Configuration 
- [ ] SFAS Backload
- [ ] EDW API 
- [ ] BC Services Card Client/Secret in SSO
- [ ] BCeID
- [ ] ESDC / NLSC

Configure Components: 
- [ ] Enable GC Notify
    - [x] Approval for PROD Version 
    - [ ] Create new PROD Key 
    - [ ] Activate Notifications Queue
- [ ] OpenShift Config - HPA config, request more resources  
- [ ] KeyCloak Config 
- [ ] Camunda setup/configuration 
- [ ] Upgrade DB and Postgres 2.9 backup container

Other tasks: 
- [ ] Email address for integrated public institutions 
- [ ] URLs for all domains/environments 
- [ ] Validate study year overlaps 
- [ ] SFAS/SIMS Sequence Number Sync / other numbers (eCert) 
- [ ] Job Timer Execution Alignment 
- [ ] Form.io Banner Post 

Key Technical Stories: 
- [ ] Camunda 8 (2.0)
- [ ] File storage (2.0)
- [ ] Virus Scanning (2.0)
- [ ] Vault (2.0)
- [ ] DB upgrade (2.X)
- [ ] Audit Logs (2.X)
- [ ] API health Check (2.X)  

Testing: 
- [ ]  Load Tests
- [ ]  Vulnerability Tests
- [ ]  Backup and Restore DB
- [ ]  Assessment Calculation Tests
- [ ]  Regression Testing 
- [ ]  Integration testing

Launch: 
- [ ] Enable BCSC Users

**Comment by michesmith** [comment]
Closing replaced with Zen ticket on the PM board #204
