### ISSUE TITLE
Institution User Provides Education Program Information

### ISSUE THREAD

**Issue by mzmichellesmith** [bcgov/SIMS#279]
**As a** *(Institution location)* **I want** *(provide information on my education program)* **So That** *(Student can Apply for that program)*

**Additional Context**
Education Programs are broken into 2 components
**Education Program**: Often referred to as the "tombstone information". This is the root information that will be approved by the ministry. Students will need to select their program before looking at their offering. Information in this component will be applicable to ALL offerings. Education programs are located at the institution account entity level and will be able to be used at any location
**Education Program Offering**: This is the component that details the specifics about an actual offering of that program. This will contain the specifics about an offering. Offerings are always specific to a location.
All fields are mandatory

**Acceptance Criteria**
Given (an Institution User), When (entering program information), Then (they have to complete the following questions for one Education Program:

** Program Information**
- [ ] "Program Name" (_free text)_,
- [ ] "Program Description" (_free text),_ 
- [ ] "Credential Type" _(drop-down list of the following: "Diploma, Certificate, Degree, Masters, Doctorate, Other (Specify)"),_
     - [ ] If 'Other Specify' is selected provide a _(free text)_ box
- [ ] "Classification of Instructional Programs (CIP) Code" _(00.0000- two integers (.) up to four integers)_
- [ ] "National Occupational Classification (NOC)" _(four integers)_ (this is optional)
- [ ] "SABC Institution Code, If this program has been approved for SABC funding before? (Optional)". (_3 letters - 1 number)_  (this field is optional on save/submit). 
- [ ] "Which regulatory body has approved your delivery of this program ?" _(Drop down list PTIB, DQAB, Private Act of B.C. Legislature, ITA, ICBC )_. 
- [ ] "How will this Program be delivered? (Select all that apply)"- Options are '_Onsite_' and '_Online- can select more than one_'. 
  - [ ] If 'Onsite' is selected the user can proceed to the "Program Course Load Calculation," question.
  - [ ] If 'Onlne' is Selected provide the following question, " Will the program also be offered and delivered 100% course load onsite?" _(Y / N)_.  
       - [ ]  If 'Yes' is selected, the user can proceed to the "Program Course Load Calculation," question.
       - [ ]  If 'No' is selected ask the following question "Will the Student earn the same number of credits in the same period as students in other StudentAid BC eligible programs delivered on site?" _(Y/ N)_ 
            - [ ]  If 'Yes' is selected, the user can proceed to the "Program Course Load Calculation," question.
            - [ ]  If 'No' is selected ask the following question, " Will they earn academic credits that are recognized at another designated institution listed in the BC Transfer Guide or other acceptable articulation agreements from other jurisdictions?"  _(Y / N)_
- [ ] "Program course load caluculation" Options are '_ Credit based_' and '_Hours based_'. 
     - [ ] If " Credit Based" is selected, the user can proceed to the "Years required to complete this program?" question. 
     - [ ] If " Hour Based" is selected, the user provides, "Average Hours of Study" _(free text- but numbers-)_
- [ ] "Years required to completed this program" _( drop-down list of years: "12 weeks to less than 1 Year," "1 Year to less than 2years", "2 Years to less than 3Years", "3 Years to less than 4 Years," "4 Years to less than 5Years," " 5 Years or More")_

** Admission Requirements**
- [ ] Provide the text, "All students must have either graduated from high school or equivalent or be 19 years of age or older for the program to be eligible. This requirement must apply to all students within a program, not only those applying for SABC funding."
- [ ] "What are the admission requirements for this program?" Options are '_ "All students must have a minimum of high school diploma or equivalent"  _' and '_" There is no minimum academic requirement"_'. 
     - [ ]  If "All students must have a minimum of high school diploma or equivalent" was selected then the user can proceed to the "English as Second Language (ESL)" section on the form.
     - [ ]  If "There is no minimum academic requirement" was selected then ask the following question: "Is the minimum age 19 and up?" _(Y/N)_
          - [ ] If ' Yes' is selected, the user can proceed to the "English as Second Language (ESL)" section on the form.
          - [ ] If 'No' is selected, display a pop-up warning message  that says "Your program is not eligible."

** English as a Second Language (ESL) Content**
- [ ] Provide the following text, " ESL Content can make up to 20% of a program, programs with more than 20% ESL are ineligible for SABC funding."
- [ ] "What percentage of the program has ESL Content?"
     - [ ] less than or equal to 20% -  _then the user can proceed to the "Program Partnerships" section on the form._
     - [  ] 20% or more - _Provide the following pop-up message_ "This program is ineligible for StudentAid BC. ESL Cannot make up more than 20% of course content".

** Program Partnerships**
- [ ] Provide the text, "If any portion of this program is offered at a partner institution, that institution must also be designated at SABC. Designated institutions are listed in the "Appy for a Loan" section of the SABC website"
- [ ] Is the program offered jointly or in partnership with other institutions? _(Y/ N)_
       - [ ] If, "No" is selected, the user can proceed to the next question, "Are all institutions you partner with for this program designated by Student Aid BC?"
       - [ ] If, "Yes" is selected, provide the following question  "Are all institutions you partner with for this program designated by Student Aid BC?" _(Y/ N)_
    - [ ] If, "Yes" is selected, the user has completed the form.
    - [ ] If, "No" provide the pop up "This program is ineligible for Student Aid BC, All partner institutions must be designated by StudentAid BC"s": _

**Final Steps**
- [ ] Given (An Institution User), When (selects submit), Then (the program information is saved all fields are mandatory except the SABC code and the NOC code.)

**Tasks**
- [x] Create DB Migration from #353
- [x] Create form.io form
- [ ] Render form
- [ ] Submit to SIMSDB and formio for new application

Figma: https://www.figma.com/file/VykmBDwobGoGvK9M5wgOvN/StudentAid-BC-App-Design-System-(WIP!!)---FreshWorks-Studios?node-id=1884%3A20472
