### ISSUE TITLE
Student Application Status Tracker for Blocked Disbursements

### ISSUE THREAD

**Issue by HRAGANBC** [bcgov/SIMS#2798]
**User Story**
As a student, I want to be notified anytime all standard required steps have been fulfilled, yet I have still not received my funding. I want to understand if my disbursements are being withheld. and for what reason, so I can understand how to resolve. 

**Description of Task**
- Add new application status tracker card explaining reason for blocked disbursements

### **Acceptance Criteria**
- [x] **Add new application status card** This should get triggered when: [ (application is enrolment = confirmed) & (there is >0 pending disbursement associated with this application) & (one of the eCert blocking conditions is = true. For example, restrictions are present which block all Full-Time funding OR all Part-Time funding; PD profile status is not verified, or MSFAA is not signed OR cancelled)
- [x] Apply same logic used for eCert validation to get the blocking conditions. Extract and Re-use the same logic from the eCert validation. 
- [x] Card should read: *(Only display content dynamically according to the conditions which is present) 
_"_Attention! You are not yet eligible to receive funding. This might be because:_ 
- _You have applied for disability funding on your application, but your disability status on your student profile has not yet been verified. Only once your status is verified will you be able to receive funding._ 
- _You have not yet signed your MSFAA number with the National Student Loans Service Center. Your MSFAA number was issued on your Notice of Assessment - you must use that number to sign your Master Student Financial Assistance Agreement with NSLSC before you are eligible to receive your funding._ 
- _Your MSFAA number has been cancelled by the National Student Loans Service Center (NSLSC). Please [contact NSLSC](https://protege-secure.csnpe-nslsc.canada.ca/en/public/contact/contact-us) to find out why it was cancelled. Until this is resolved, you will not be eligible to receive funding._
- _You have a restriction on your account making you ineligible to receive funding._
_Please contact StudentAid BC if you still require assistance in identifying the cause of this issue, and help resolving the issue. "__
- [x] E2E tests
- [x] When warning card is displayed, change process bar colour/icons accordingly.

**Comment by dheepak-aot** [comment]
@HRAGANBC @Joshua-Lakusta @CarlyCotton 

From my understanding on reading the story, it is a single card having the reasons of blocked disbursements.

Is my understanding wrong ?? and is it multiple cards?

**Comment by HRAGANBC** [comment]
@dheepak-aot @lewischen-aot 
1. Yes, it is a single card. But the content of the card is dynamic and only includes the actual reason(s) for the blockage. 
2. Thanks for pointing this out. We'd like to add the first two scenarios, but not the third (COE). Use the following content: 

> - Your SIN is invalid and your funding cannot be issued. Contact StudentAid BC for assistance. 

> - Your current funding assessment would exceed your allowable lifetime limit for Part-Time Canada Student Loan. Your assessment must be adjusted to stay within your lifetime limit. Contact StudentAid BC for assistance. 


@Joshua-Lakusta FYI

**Comment by lewischen-aot** [comment]
@HRAGANBC @Joshua-Lakusta @CarlyCotton 

Thank you @dheepak-aot for raising the questions. I have two questions on the story, and it would be nice to get some clarification from the business team as well.

1. The first AC in the story is to "Add new application status card This should get triggered when: [ (application is enrolment = confirmed) & (there is >0 pending disbursement associated with this application) & ...". Please verify with me whether we are adding new tracker card on the enrolment status bar (as shown in the image below) or the completed status. Thank you @dheepak-aot for pointing it out. 
<img width="1105" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMGtEQlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--0f042c567a16e8f2ea3b2135bbf33e1243980804/image.png" alt="image.png" />

2. The third AC is that "Card should read: *(Only display content dynamically according to the conditions which is present)". If the student's disability status is not verified and the MSFAA number is not yet signed, should we display one or two cards for the ineligible reasons? The current PR shows 1 card for each ineligible reason. If we only display one card, should we display both reasons in the content of the card or just one?

**Comment by andrewsignori-aot** [comment]
> @dheepak-aot @lewischen-aot
> 
> 1. Yes, it is a single card. But the content of the card is dynamic and only includes the actual reason(s) for the blockage.
> 2. Thanks for pointing this out. We'd like to add the first two scenarios, but not the third (COE). Use the following content:
> 
> > * Your SIN is invalid and your funding cannot be issued. Contact StudentAid BC for assistance.
> 
> > * Your current funding assessment would exceed your allowable lifetime limit for Part-Time Canada Student Loan. Your assessment must be adjusted to stay within your lifetime limit. Contact StudentAid BC for assistance.
> 
> @Joshua-Lakusta FYI

@HRAGANBC can we have a specific message for when MSFAA is cancelled vs not signed yet? We have the information handy and it would be just the case of defining its content.

**Comment by CarlyCotton** [comment]
@lewischen-aot @andrewsignori-aot  Can the cancelled MSFAA scenario receive this message? (And update the not-signed message to not reference cancellation)

> Your MSFAA number has been cancelled by the National Student Loans Service Center (NSLSC). Please [contact NSLSC](https://protege-secure.csnpe-nslsc.canada.ca/en/public/contact/contact-us) to find out why it was cancelled. Until this is resolved, you will not be eligible to receive funding.

>You have not yet signed your MSFAA number with the National Student Loans Service Center. Your MSFAA number was issued on your Notice of Assessment - you must use that number to sign your Master Student Financial Assistance Agreement with NSLSC before you are eligible to receive your funding.

FYI @HRAGANBC

**Comment by andrewsignori-aot** [comment]
> @dheepak-aot @lewischen-aot
> 
> 1. Yes, it is a single card. But the content of the card is dynamic and only includes the actual reason(s) for the blockage.
> 2. Thanks for pointing this out. We'd like to add the first two scenarios, but not the third (COE). Use the following content:
> 
> > * Your SIN is invalid and your funding cannot be issued. Contact StudentAid BC for assistance.
> 
> > * Your current funding assessment would exceed your allowable lifetime limit for Part-Time Canada Student Loan. Your assessment must be adjusted to stay within your lifetime limit. Contact StudentAid BC for assistance.
> 
> @Joshua-Lakusta FYI

@HRAGANBC can you please update the ACs to include these also?

**Comment by HRAGANBC** [comment]
@andrewsignori-aot Updated the AC's, thanks
