### ISSUE TITLE
Verify and/or Fix Code/DB Inconsistencies/Migrations

### ISSUE THREAD

**Issue by abschwenker** [bcgov/SIMS#297]
User authorized roles drop down. Remove obsolete roles (Location-manager, primary contact)

Additional Context
- Change previous migration scripts, do not create a new migration

Technical Tasks 
--------------------------------------------------
**Task 1**
Some tables are not using Serial/Integer properly causing PK sequence to be out of sync. 
- [ ] Review all tables as per below (search in VS for serial keys if they are using a PK)
- Tables should use INTEGER when using fixed lists. EG.
![image.png](https://images.zenhubusercontent.com/5fce9c77aab275719112dc74/5b6e9fd6-307e-4134-a3ce-1413e5310d7b)
- Tables should use SERIAL when using non fixed lists and do NOT provide IDs while insert initial data. EG
![image.png](https://images.zenhubusercontent.com/5fce9c77aab275719112dc74/2e191963-34c3-4c66-b548-e77c2d73ef77)
- Example issue: sims.restrictions
![image.png](https://images.zenhubusercontent.com/5fcebe3c076e6aaed83693fb/5e28b45c-9910-4a77-ac84-049c578a688e)
- [ ] Reintroduce the migration seed for provincial restrictions that were removed due an issue probably caused by the first item in this ticket (please see -- migration file https://github.com/bcgov/SIMS/pull/950/files#diff-84ab6565ff9036c32c8715b6e338b0f55b005d4eaa7541a61e2143b5ac4754b2).
- [ ] Execute a local test removing completely the DB resources (make local-clean) and executing the migrations.

Ref:
https://stackoverflow.com/questions/244243/how-to-reset-postgres-primary-key-sequence-when-it-falls-out-of-sync
https://bobcares.com/blog/postgresql-error-code-23505/

**Comment by andrewsignori-aot** [comment]
Please find below the output from the devs meeting.

Interface names - with or without ("I")
- Do not use "I"

Naming DTO objects with Dto suffix
- Use .dto. in the file name (check further Nestjs)
- Add Dto suffix
- In general interfaces for response and classes for input
- Every object leaving/arriving at API should be a Dto

Test files (Unit and E2E)
- Unit Tests alongside the file being tested (same for API/WEB)
- Need to change the Web package. API package is already doing it.
- API E2E - Keep alongside with module under a __tests__ folder.
- Cypress - Keep it global to the solution, outside web project as a separated package.

Review Types folder for services
- Follow the same Contract model from the Web package
- Types that are not shared should be kept as local

**Comment by dheepak-aot** [comment]
The following provincial restrictions have been inserted manually to DEV and TEST DB. [https://app.zenhub.com/files/319429847/49c03c0c-1a04-4d31-891c-c7affdf68992/download](https://app.zenhub.com/files/319429847/49c03c0c-1a04-4d31-891c-c7affdf68992/download)

**Comment by dheepak-aot** [comment]
During the test run of #747(Importing federal restriction from file to SIMS DB) a number of federal restrictions got imported to the restrictions table in dev. These entries are redundant with Federal restrictions given in [Restriction List vDec 8'21.xlsx] in DEVS wiki. While preparing the initial insert or seed script we have to fix this in a way that federal restrictions from xlsx file(which has description) make it to the table.

**Comment by henryoforeh-aot** [comment]
I validated all the technical tasks and also verified that they have been done. I am moving the status of this ticket to review.
