### ISSUE TITLE
Generate e-Cert Feedback File Error Application Tracker Card

### ISSUE THREAD

**Issue by andrewsignori-aot** [bcgov/SIMS#3073]
#2536 is a related ticket handling how these errors are communicated to student

**Description of Task**:
Trigger specific actions anytime we receive eCert feedback file records for specific student records. 

**Acceptance Criteria**
- [x] Create a new Student Application Status Tracker Card consistent with the above section anytime errors are detected. Application Status Tracker Card should read: 
> **There is an issue with your funding request**
> Your request for funding sent to NSLSC was initially rejected because of errors with your assessment and/or with your account. Please contact StudentAid BC for assistance in resolving this issue. Please note, this message may remain after the issue has been resolved.

**Technical**
- [x] Display new card only for the application status tracker `Completed` status.
- [x] Show the warning application tracker card when there are errors associated with any application's current disbursements (first or second). Display the card on top of all existing ones.
- [x] Application status tracker progress bar should be adapted accordingly to display the warning color and warning icon.
- [x] Only display the card if the existing errors are flagged as `block_funding` in table `sims.ecert_feedback_errors`.
- [x] E2E tests.

**Context:**
The federal service provider (NSLSC/Finastra) sends a daily eCert Feedback file which sometimes contains error codes for particular applications disbursement requests. These error codes indicate there was at least one error in the list of validations which exist on the NSLSC side. For e.g., the address listed on a student's application is not recognized, or a student is missing a first name. 

Some of the errors do not block the disbursement from being issued, but others do. For any errors which block disbursement, the student's application and disbursements are now completely in limbo and will not get resolved unless someone within SABC takes an action to resolve. However, without knowledge of which students have errors, there is no way for SABC staff to know which applications need attention.

**Comment by CarlyCotton** [comment]
@dheepak-aot Updated the AC to include a header text for the banner.

**Comment by dheepak-aot** [comment]
Thanks @CarlyCotton
