### ISSUE TITLE
6.2.5 Manage Web Portal Updates 

### ISSUE THREAD

**Issue by michesmith** [bcgov/SIMS#3197]
**As a** *developer interested in the best maintainable solution* **I want** *to have the web package as updated as possible* **So That** *keeping updates applied will be feasible*.

**Acceptance Criteria**
- [ ] Upgrade packages related to the web package (web portal).
- [ ] Remove packages no longer needed.
- [ ] Replace temporary UI frameworks (PrimeVue) and keep a single UI framework in the solution.
