### ISSUE TITLE
Ministry portal: Add name to all assessment pages

### ISSUE THREAD

**Issue by JerPearson** [bcgov/SIMS#3287]
As a Ministry user I need to see the students identifying information on the 'assessment page', 'view assessment' page, and 'notice of assessment' page.

## Acceptance Criteria

- [x] The following information should be displayed across the top of the 'assessment page', 'view assessment' page, and 'notice of assessment' page:

> Name: 
> Application number:
> Institution:
> Study dates:
> Type: 

- [x] If there is no offering attached (PIR/draft/etc), do NOT show any OFFERING data (study dates, intensity)
- [x]  Please update all fields to the above content.  
- [x]  Mock up #1 shows the 'view assessment' page and how the information should be formatted and displayed, with name added to the left of application #.
- [x]  Mock up #2 shows the 'notice of assessment' and where the fields should be added
- [x]  Mock up #3 shows the 'assessment' page and where the information should be displayed
- [x]  For draft applications, this would result in Student Name only (no offering data / no app number)

#1
<img width="1411" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBOU9EQmc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--d9ba3b2e3120eb66cafdbaa7d9d828b09caa907c/image.png" alt="image.png" />

#2
<img width="1079" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBK2IxQmc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--167cca7209e62c5b0ab258ad2de16b54d94831d8/image.png" alt="image.png" />

#3
<img width="1436" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBOWVEQmc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--29983475996c288214a24a57f64636b83de06a09/image.png" alt="image.png" />

**Technical**
- [x] Consider below technical items as suggestions. Deviations or better approaches can be checked with the Team and are welcomed.
- [x] Adapt the existing endpoint `aest/application/:applicationId` to return the header information.
  - [x] Create a query string parameter to allow optionally loading the  `dynamic application data`, e.g. `aest/application/:applicationId?load-dynamic-data=false`.
    - [x] Do not process the `generateApplicationFormData` case `load-dynamic-data=false`. SQL query already has a parameter to optionally load the form data.
    - [x] Keep the default controller behavior if the query string parameter is not present (`load-dynamic-data=true`).
    - [x] Create a new DTO extending from `ApplicationBaseAPIOutDTO` and add the extra properties.
      - `studentFullName`: use the `getUserFullName` method.
      - `applicationOfferingIntensity`, if the offering is not present, hide it.
      - `applicationStartDate`, if the offering is not present, hide it.
      - `applicationEndDate`, if the offering is not present, hide it.
      - `institutionName`: institution name from the `sims.applications.location_id`. Get the institution name using the location ID. This would allow us to show the institution name even for PIR (the same is not desirable for offerings). If not present, hide it. User the institution `operatingName` (to be confirmed).
- [x] Create a new component in Vue to display the header. Suggested name: `application-header-title`.
  - [x] Create the component inside the `components/aest/students` folder.
  - [x] User the existing `header-title-value` to display the key/value pairs.
  - [x] Component should receive the application ID as a property and use it to call the API and render the information using the `header-title-value`.
- [x] E2E Tests
  - Endpoint does not have E2E tests. Create the below E2E tests.
    -  [x] Should get the application information including its dynamic data when the load-dynamic-data parameter is true.
    -  [x] Should get the application information excluding its dynamic data when the load-dynamic-data parameter is false.

**Comment by CarlyCotton** [comment]
@katrina-aot-git Updated mockup #2 regarding the NOA placement. Significant changes are coming to the NOA page content within the page and the previous area circled will be updated then.

FYI @andrewsignori-aot @JerPearson

**Comment by CarlyCotton** [comment]
@katrina-aot-git Based on the comments in the PR channel, I've updated the AC re PIR expectations and added an AC re Draft expectations

FYI @andrewsignori-aot @dheepak-aot
