### ISSUE TITLE
Request Permanent Disability 

### ISSUE THREAD

**Issue by mzmichellesmith** [bcgov/SIMS#337]
Students can request permanent disability status at the account level 

SABC Provides First Name, Last Name, DOB and SIN to ATBC
Permanent Disability status is pending until status is received back from AT BC

**Acceptance Criteria**
- [ ] Given (A Student), When (they want to request PD), Then (they can select Request Permanent Disability Status)
- [ ] Given (A Student), When (they select PD Status), Then, we send First Name, Last Name and DOB and SIN to AT BC and the Students PD Status is set to Pending)
- [ ] Given (ATBC), When (have confirmed PD Status), Then, (the students PD Status is set to 'PD Confirmed /' PD Denied'
- [ ] Given (ATBC), When (have confirmed PD Status), Then, (we capture the date of status change

**Tasks**
- [ ] Create button on profile to "Apply for PD status"
- [ ] Create API calls to create client (Record) 
- [ ] Create API calls to Retrieve client status
- [ ] Create table for PD Status with "PD Status" "Date Sent" "Date updated"\- [ ] Update "PD Status"
- [ ] Scheduler to Update "PD Status"
- [ ] Update on Account Creation PD lookup (Code exists for PD lookup on SFASDB on account creation)
- [ ] Create New Openshift Secrets

**Comment by roopfw** [comment]
Initial Discussion Workflow: https://www.figma.com/file/lkLlMiqSYamaaHIaB5CtaW/StudentAidBC-PD-Workflows?node-id=0%3A1

**Comment by abschwenker** [comment]
The pd consultation was moved from GET to POST
The client is now accepting e-mail (required), mobile phone (optional) and address (optional)

For PD consultation you need just to send the same information as before but in JSON format with the parameter id like this:
{
  "id": <value>
}

For the client this is the new format:

{
"SIN":"123456789",
"firstName": "Client",
"lastName": "Test",
"birthDate": "MM/DD/YYYY",
"email": "someone@example.com",
"mobile": "(999)-999-9999",
"address": {
"street": "1234 Fake Street",
"city": "Vancouver",
"province": "BC",
"country": "CA",
"postalCode": "V6P 2T1"
}
}

**Comment by abschwenker** [comment]
PD Notes.docx in SharePoint-DEVS
