### ISSUE TITLE
NOA - Displaying $0 award / not eligible 

### ISSUE THREAD

**Issue by CarlyCotton** [bcgov/SIMS#3382]
**User Story**
As a student, I may apply for funding and am not eligible for any funding or am eligible but only for $0 total. In these cases I need a way to show that I have done the application process and there may be appeals that I need to submit in order to show I am eligible or eligible for more than $0. 

**Acceptance Criteria**
- [x] Similar to #2706: Block student from accepting the assessment when the total award is $0/not eligible for awards.
- [x] When blocking acceptance, provide this warning banner information:
> Your application has been assessed and no funding has been awarded. If you believe this is an error, please review your application to ensure it is accurate or contact [StudentAid BC](mailto:studentaidbc@gov.bc.ca).
- [x] Still display NOA and assessment details on $0/not eligible assessments.
- [x] See Additional Context: On $0 total award with 2 disbursements, still allow the workflow to save the disbursements. Remove the condition from the "Configure Payload for 18 weeks or more" inside parttime-configure-disbursement to allow a $0 dollar disbursement to be saved.
- [x] If multiple blocking conditions display all information under the same banner.
- [ ] Add header for the banner with acceptance blockers: **Your assessment cannot be accepted yet**
- [ ] Adjust the order of the banners shown to put this below the two profile level banners (restrictions and SIN)
- [ ] Only show this banner when the "Accept assessment" is shown. Do not display if the accept button is not displayed.

**Additional Context**
> the issue today morning in my demo, that the application is not proceeding after the income verification is due to the fact that disbursement schedule was not created for it. This is happening only for scenarios when the application has 2 disbursement and no eligible awards,

<img width="1858" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBelErQlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--3cb6eac62b55c303f9a7676a4ae3ccc30ecc7bb8/MicrosoftTeams-image%20%283%29.png" alt="MicrosoftTeams-image (3).png" />

**Technical**
- [x] Ensure that an assessment with $0/no eligible with two disbursements can still display its NOA.
<img width="1048" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNUZ6QlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--d200d1e4577cd183859267c5da8eacf78d26c959/image.png" alt="image.png" />
- [ ] Add a service method to check if the total award value(Total estimated award) is > 0.
- [ ] Enhance the API(implemented in #2706) [getApplicationWarnings](https://github.com/bcgov/SIMS/blob/6dfebde89ce04564397d12da44fe93b8f5bc2cf5/sources/packages/backend/apps/api/src/route-controllers/application/application.students.controller.ts#L230) to return the total estimated award value. 
- [x] In the UI, block student from accepting the assessment and display a warning banner in addition to the existing warnings and blocking implemented in #2706.
- [x] Implement the server side validation for accepting the assessment [confirmAssessmentNOA](https://github.com/bcgov/SIMS/blob/9c9cbf39c0cb08c2ca3587a62f2c51b87356c0a3/sources/packages/backend/apps/api/src/route-controllers/assessment/assessment.students.controller.ts#L84) to check for total estimated award value. 
- [x] During the implementation of #2706, server side validations for the scope of the ticket was missed. Implement the server side validation from #2706
- [x] Use the banner component and also the specific banner `slot` in the `full-page-container`.
- [x] E2E tests
  - [x] Create more scanrios to test the new condition. 
    - Suggested at least one scenario where the dollar amount will be 0(zero) and another with only `non-eligible` awards.

**Comment by andrewsignori-aot** [comment]
@Joshua-Lakusta trying to double-check the understanding, are we not going to have the $0 dollar amount added as one more blocking e-Cert condition or is it still on the table?

**Comment by dheepak-aot** [comment]
Updated the following technical ACs. <img width="855" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBOGY4QlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--4e5481bc3f5be09cc406e7973c9bc4576a31e51b/image.png" alt="image.png" />

**Comment by CarlyCotton** [comment]
@andrewsignori-aot  Still on the table - it is on a separate ticket though #3416

**Comment by andrewsignori-aot** [comment]
@CarlyCotton trying to double-check the behavior when displaying multiple banners in the NOA.
Below would be my recommendation and I believe that it would be aligned with the requirement.

The first two banners "Your account has a restriction" and "Your account has a warning" are banners that can potentially be displayed in any student page.
The last banner is the one with the possible multiple blocking e-Cert conditions. It is my understanding that it should be displayed as in the image below or before the "Your account has a restriction". Either way, it should be between the "page header" and its "body". Does it make sense?

Currently, its title is just "Waning", can we adjust its title to something like "Your assessment has warnings preventing it from being accepted".

<img width="715" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMWdKQmc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--6766bf043ea19d8382bcbda5472861bc06b0705b/image.png" alt="image.png" />

**Comment by andrewsignori-aot** [comment]
@CarlyCotton there are conditions to display the "Accept assessment" button, as listed below, should we display the banner following the same condition? It is a quick check.
- Application: Assessment;
- NOA Approval Status: Required;
- Assessment is the application's current one.

**Comment by CarlyCotton** [comment]
@andrewsignori-aot 

1. Can we update the header on the warning to "**Your assessment cannot be accepted yet**"?
2. The updated placement of this warning banner to be lower priority than the other two profile-wide ones is fine.
3. Yes, this banner should be tied to the display conditions of the Accept button. (No need to view these errors if it has been accepted or is not the most recent one).

**Comment by andrewsignori-aot** [comment]
> @andrewsignori-aot
> 
> 1. Can we update the header on the warning to "**Your assessment cannot be accepted yet**"?
> 2. The updated placement of this warning banner to be lower priority than the other two profile-wide ones is fine.
> 3. Yes, this banner should be tied to the display conditions of the Accept button. (No need to view these errors if it has been accepted or is not the most recent one).

@CarlyCotton are you planning to update the ACs in some way to reflect the above?

**Comment by CarlyCotton** [comment]
@andrewsignori-aot  Updated.
