### ISSUE TITLE
Determine SAVE DRAFT Student Application

### ISSUE THREAD

**Issue by mzmichellesmith** [bcgov/SIMS#356]
**TASKS**
- [x] Student able to save an unvalidated application to SIMSDB with Draft Status
- [x] Validate on Submit that PY is active
- How to bypass validations?? 

Validate before is student can open draft. A Student should not be able to renavigate to Inactive PY drafts. (Include details of PY dates) -Seperate Ticket for Biz rules

**OLD Ticket with PR**
---------

Requirements Questions:
1) Multiple Drafts? No. MVP only one draft version. - Multiple Versions MAY be a consideration post MVP but not a high priority.
2) How long do we keep the Draft? -  If the Program Start Date is no longer feasible- it is removed. If a new Program year has started- we do not keep the draft.  Tie it to Program Year if they did not select program dates.
3) Once it's Submitted do we Remove the Draft?. YES. Now it's a Submitted Application (no longer a Draft)
4) Automated Draft Saving? No. A question should be asked to Save the Application.
5) UX /UI Design Where do they go to view the draft (page)- This is not Ready- TBD
6) Where do we start for Editing the Draft (First Screen or where the student left off)?  TBD
7)How many fields required to initiate a Save Draft?  1 question.

8) What happens when we update after Submit (this is another User Story).

Acceptance Criteria
- [ ] Determine and Define Save Draft Approach (Confirm Solution Recommendations to Alys)
 --- Determine How to save application data in OUR database
