### ISSUE TITLE
Copy of CAS Integration 3 - Create new Supplier, Create new Site, & Update Existing Site

### ISSUE THREAD

**Issue by CarlyCotton** [bcgov/SIMS#3602]
### **User Story:** 
As an SABC Finance team member (Ministry user), I want to ensure the CAS records and SIMS records of a student match by adding new supplier if it doesnt exist, creating a new address if SIMS address doesn't match the CAS one, and overwriting/updating the address info if the SIMS address doesn't match the CAS one. 

### **Create New Supplier and Site**
- [ ] If the Get Supplier Response Returns a '404 - not found' error, then execute the 'Create Supplier and Site' transaction
    - [ ] See [Supplier Web Service RESTful Client Onboarding v02_01.pdf](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBOXpWQkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--361bbb0afd9232c66288a57ce767a1a8d478f535/Supplier%20Web%20Service%20RESTful%20Client%20Onboarding%20v02_01.pdf) page 20 for details.
    - [ ] This update can only be pushed to CAS during the scheduled business hours, per ticket #3327
    - [ ] Call using **command 1** (see below). If field is not mandatory and SIMS doesn't have that data, leave null (except for SIN - always include that)
    - [ ] Use the SIMS profile address in the command, but format according to [Individual Supplier Web Service Field Requirements (All Requests) JAN2023.xlsx](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNGJYQkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--bd785e77d67f3e11bfd591da13f2baae828b7436/Individual%20Supplier%20Web%20Service%20Field%20Requirements%20%28All%20Requests%29%20JAN2023.xlsx) 
    - [ ] If successful response, then update SIMS CAS table with the returned `supplierNumber`, `SiteCode` and any other required info and set `isValid`=true
    - [ ] If error response, then defer to ticket #3258
    

### **Update Existing Supplier Site**
 - [ ] If the 'Get Supplier' Transaction returned address info which does not perfectly match against the address info on a student SIMS profile AND the Supplier and Site status is _not_ protected, OR if a student updates their profile and address information in SIMS, then execute the "Update Existing Supplier Site" transaction
     - [ ] See [Supplier Web Service RESTful Client Onboarding v02_01.pdf](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBOXpWQkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--361bbb0afd9232c66288a57ce767a1a8d478f535/Supplier%20Web%20Service%20RESTful%20Client%20Onboarding%20v02_01.pdf) page 28 for details.
    - [ ] This update can only be pushed to CAS during the scheduled business hours, per ticket #3327
    - [ ] Call using **command 2** (see below) If field is not mandatory and SIMS doesn't have that data, leave null (except for SIN - always include that)
    - [ ] If multiple addresses are returned in the Get Supplier call, this transaction should overwrite whichever address has `status`=ACTIVE (typically the first one in the array)
    - [ ] Do NOT execute this transaction if the Get Supplier returned a response with `SupplierProtected`=True AND/OR `SiteProtected`=true. Instead, defer this to the error handling ticket #3327

***Technical Context***

Sample CURL to create
```console
curl --location '${BASEURL}/cfs/supplier/' \
--header 'Content-Type: application/json' \
--header 'Authorization: Bearer ${TOKEN}' \
--data-raw '{
    SupplierName: '\''Skywalker, Leia'\'',
    SubCategory: '\''Individual'\'',
    Sin: '\''422233197'\'',
    SupplierAddress: [
    {
        AddressLine1: '\''1012 Douglas St'\'',
        City: '\''Victoria'\'',
        Province: '\''BC'\'',
        Postalcode: '\''V8W 2C3'\'',
        Country: '\''Canada'\'',
        EmailAddress: '\''stephen.laws@gov.bc.ca'\'',
    }]
}'
```

Response:
```console
{"SUPPLIER_NUMBER":"2007638","SUPPLIER_SITE_CODE":"[001] ","CAS-Returned-Messages":"SUCCEEDED"}
```

***Business Context***
---
### **Create New Supplier and New Site Transaction Details**
**Command 1 - Create New Supplier and Site Call**
{
    "SupplierName":"SMITH, SUSAN",
    "SubCategory":"Individual",
    "Sin":"",
    "BusinessNumber":"",
    "SupplierAddress":[
       {
           "AddressLine1":"5522 Oyama Lake Rd",
           "AddressLine2":"",
           "AddressLine3":"",
           "City":"Lake Country",
           "Province":"BC",
           "Country":"CA",
           "PostalCode":"V4V2C9",
           "EmailAddress":abc@xyz.com,
           "EftAdvicePref": 

       }
    ]
}

**Successful Response**
{
    "Supplier_Number":"123456789",
    "Supplier_Site_Code":"001",
    "CAS-Returned-Messages":"SUCCESS"
}

**Error Response**
{
    "Supplier_Number":"123456789",
    "Supplier_Site_Code":"001",
    "CAS-Returned-Messages":"Error Message"
}

---
### **Update Existing Supplier Site**
**Command 2**
{
   "SupplierNumber":"2002492",
   "SupplierAddress":[
     {
        "SupplierSiteCode":"001",
        "AddressLine1":"3350 CLEARBROOK RD",
        "AddressLine2":"",
        "AddressLine3":"",
        "City":"ABBOTSFORD",
        "Province":"BC",
        "Country":"CA",
        "PostalCode":"V2T4T4",
        "EmailAddress":"abc@xyz.com",
        "EftAdvicePref":"E"
     }
  ]
}

**Success Response:**
{
 "Supplier_Number":"123456789",
 "Supplier_Site_Code":"001",
 "CAS-Returned-Messages":"SUCCESS"
}

**Error Response**
{
 "Supplier_Number":"123456789",
 "Supplier_Site_Code":"001",
 "CAS-Returned-Messages":"Error Message"
}

**Comment by CarlyCotton** [comment]
Takeaways: student change last name
<img width="806" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNjlmQmc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--685817dd9156082bbd4e482337a8532f132ea0ab/image.png" alt="image.png" />
multiple supplier/site and address updates from SIMS
confirm with CAS re changing last name/sin and multiple supplier numbers for the same person. _Can we create new sites/new suppliers?_
