### ISSUE TITLE
Partner Current year income application question

### ISSUE THREAD

**Issue by Joshua-Lakusta** [bcgov/SIMS#3615]
As a student I want to be able to submit my application with my partners current year income through an exception path question. The question needs to be post the BCSC question but modify the outcomes as sub question. This is important so that students can receive their correct assessment. 

This is linked to the change request built in ticket #3620 

# **Acceptance Criteria**

### **New partner BCSC question process**

- [x] Add a sub question after partner BCSC question on the partner tab. This question will always be asked regardless of the answer to yes or no for BCSC. It should always appear anytime the partner tab appears and the two questions together will determine what happens next for the application logic(see image below of branching paths)
- [x] Question can be embedded under the current question for BCSC as per this image
<img width="1241" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBd2lrQnc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--139a65edd6a8a6e46c2a4f779b9f0e087c768fdb/image.png" alt="image.png" />

- [x] Content for new question

> Do you want to declare your spouse/common-law partner's estimated current year income? (If your spouse/common-law partner has had, or anticipates having a significant decrease in income for "YEAR", you may request to be assessed using your spouse/common-law partners estimated income.)

- [x] Replace "YEAR" with dynamic calculation YEAR =  first year in program year (2023-2024 would be 2023)

- [x]  2 radio option outcomes for this question as yes or no
- [x]  If the answer is no then follow previous processes partner portal banner if they selected yes to BCSC or self declare path if the stated no to BCSC
- [x]  If they answer "yes" to the new question it should take them to a new self declare path that has the estimated current year income question replacing the normal income field question.
- [x]  Answering yes will hide the tax return income input
- [x]  The banners attached to the BCSC question must be delayed until both questions have been completed and the path forward is decided. 

See image for baseline logic for pathing not for use in work flows just showing the logic
<img width="986" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBKzhSQnc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--3fec993e46bc044c9e5641c263fc8da4ebb17bde/image.png" alt="image.png" />

### **Modified self declare path**

- [x] Answering yes to the new question opens a modified self declare path that will add the new additional estimated partner current year income exception field and support fields (this will mirror the question from the change request version in ticket #3620) 
- [x] Do not show "i have been authorized" check box and content when Yes is selected for the new question
<img width="1123" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBN0NqQnc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--b37ec704b61624585abf4f3468340def35f0517e/image.png" alt="image.png" />

- [x] New path will be an exception path question and will trigger new exception 
- [x] Please make these changes to both FT and PT. For full time we will just be creating the new current year income path and it will mirror the PT version. Additional work will be completed in another ticket to flesh out the content for full time.
- [x] Change content at point #1 in image below to (Change this for both the new path and the normal self declare path)

> Partner financial information

- [x] Change the content for point 2 to the following 

<img width="625" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBd0NxQnc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--d93fb7aec7a05071f8a040d23eddeeea8e738097/image.png" alt="image.png" />

- [x] The following income should be above the current year income field connected to the new data form
> Add your spouse/common-law partner's actual income from the beginning of YEAR up to the date their income change, along with the estimated income for the remainder of the year, to calculate their total estimate income for the current year.

- [x] Replace "YEAR" with dynamic calculation YEAR =  first year in program year (2023-2024 would be 2023)

- [x] Add income entry field that will represent a new value to be created and named by dev doing the ticket (partnerestimatedincome) 
- [x] Income field should follow the same rules as the estimated student income version

- [x] **Heading above the income entry field should state:** point #4

> My spouse/common-law partner's estimated current year income is:
<img width="1285" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNzQ3Qnc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--366e063a6dfa299fceb04fa588d90a2259f31a4f/image.png" alt="image.png" />

- [x] There needs to be a section for the reasons for change in estimated income with five options and only one can be selected

**Content:**

> Select the reason for your spouse/common-law partners significant decrease in income.
> - Medical illness or injury
> - Family emergency (e.g., death or injury)
> - Natural Disaster
> - Layoff, strike, lockout or other reduction in earnings beyond the family's control
> - Other

- [x] Add content for uploader content for documentation for uploader:

> Upload supporting documents for spouse/common-law  partners "dynamic year (app program year - 1 (2024-2025 would be 2024))" estimated income.
> Please provide supporting documentation for your request to use current year estimated income for your spouse/common law partner.
> Provide the following:
> 
> A letter explaining the circumstances that meet one or more of the Criteria (see above)
> Provide at least one of the following:
> 
> All relevant supporting documentation of the circumstance(s) (medical records, letter from the physician, record of employment, layoff or strike, invoices from damages, etc.).
> The more recent CRA Income Tax Return and income information for the year matching the student financial assistance application number (with relevant supporting documentation to show the decrease in income), if available.
> All relevant supporting documentation of estimated total income for the year matching the student financial assistance application number, if applicable (pay stubs, invoices, bank statements, Employment Insurance benefit statements, Record of Employment, etc.).
---
### **Calculation Updates**
- [x] The new question will replace the base partner income question on this current year estimated income path
- [x] This new income will be set above all other incomes in the priority list (same as student estimated current year income) and will require a new variable to reflect this amount in Camunda. (similar to process completed for student estimated current year income)
Update calculations

Current
```
if
  partner1CRAReportedIncome = null
then
  calculatedDataPartner1TotalIncome
else
  partner1CRAReportedIncome

```
```
if 
  studentdatacurrentyearpartnerincome = null  (This is a suggested name for the value)
then
    if
        partner1CRAReportedIncome = null
    then
        calculatedDataPartner1TotalIncome
    else
  partner1CRAReportedIncome
else
   studentdatacurrentyearpartnerincome
```

- [x] This field will need to be updated based on the changes from the change request ticket as well as making sure we update the priority list to include the new value whatever it is named

<img width="284" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBL2s3Qnc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--2caa44a0571cde6711ed1c578b743e2bc85eb7b3/image.png" alt="image.png" />

### **Ministry exception update**

- [x]  Add "Partner current year income" to the list {data.exceptionNames.length} and show to ministry user when this exception is pending ministry action.

<img width="990" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBekZMQnc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--1eac930683c36f46e1aa2573713236ad09f675e4/image.png" alt="image.png" />

**Technical**
- [x] Adjust `assessment-gateway` to prevent supporting user creation, as shown in the below image. Adjust the label to reflect the most recent logic.
<img width="823" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMzVXQnc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--7c165ccfde2efb6c85511182163870406483b789/image.png" alt="image.png" />
- [x] Exception creation is handled dynamically. Ask for help if you have never done it before.
- [x] No `fulltime-assessment-*` workflow changes are expected now.
- [x] Workflow E2E tests.

**Comment by dheepak-aot** [comment]
@Joshua-Lakusta as discussed, if a FT application is submitted with student having a partner and student reporting partner's current year income, then this specific scenario breaks the `fulltime-assessment` workflow as fulltime assessment workflow is not updated to choose current year income over the tax return income.
