### ISSUE TITLE
$0/Ineligible Assessment - Student Tracker Cards

### ISSUE THREAD

**Issue by CarlyCotton** [bcgov/SIMS#3683]
Related to #3453
**User Story**
As a student, I want to have consistent messaging about what is happening with my application. If I have an accepted assessment that has COE Required and ends up becoming $0/ineligible, I don't want to see the tracker cards about COE pending Institution and I want to see a tracker card that is similar to the message that blocks students from accepting a $0 assessment.

**Acceptance Criteria**
When Assessment = Accepted & Total Disbursement is $0/Ineligible & COE=Required: 
- [ ] Do NOT show any COE Required tracker cards
- [ ] Display a NEW error tracker card when:
    - [ ] **Header**: Your application is currently not eligible for funding
    - [ ] **Content**: Your application has been assessed and no funding has been awarded. If you believe this is an error, please review your application to ensure it is accurate or contact StudentAid BC.

**Comment by Joshua-Lakusta** [comment]
Needed as we are giving false information which could be hugely detrimental to students.
