### ISSUE TITLE
Past 6 week deadline tracker card

### ISSUE THREAD

**Issue by Joshua-Lakusta** [bcgov/SIMS#3753]
**As a student I want to be able to see through a tracker card when I am not eligible for funding due to my application being past the 6 week deadline. This is important as current state implies to students that money could be on its way when really they are completely stalled without completing an appeal.
**Acceptance Criteria**
- [ ] Create a new yellow warning tracker card that mirrors the warning inside the application for when a student is in this state. 
- [ ] Have this tracker card appear anytime the students application is pending a funding after end date exception
- [ ] content for tracker card 

> ### Study period not eligible for funding
> The dates you have entered are no longer eligible for funding. To receive funding for this study period, you will need to seek approval from StudentAid BC. Once you have submitted your application, please use the following link for information on the https://studentaidbc.ca/sites/all/files/form-library/appeal_fundingafterenddate.pdf.

REPLACE link id with following text 

> funding after end date appeal

**Additional Context**

**Comment by CarlyCotton** [comment]
@Joshua-Lakusta Is a(nother) tracker card the right solution? We already have an exception tracker card that could maybe be used better to dynamically indicate which exceptions are being reviewed?
<img width="1283" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBeXdWQnc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--b6b6138cec596f6404e45e5d4ee9e4ad8d03897e/image.png" alt="image.png" />

**Comment by Joshua-Lakusta** [comment]
Flagged as critical but low critical. Can be bumped to 3.1 if needed to release in time.
