### ISSUE TITLE
Add Institution User Access type authorization to pages

### ISSUE THREAD

**Issue by mzmichellesmith** [bcgov/SIMS#376]
**Acceptance Criteria**
- [x] Manage institution (Including Institution Details, Manage Locations, Manage Users, Manage Designation) is accessible only by (Institution Admin)
- [x] Location (Including Dashboard, Location Details, Manage Programs, Manage Student Applications) is accessible by (Institution Admin, Location-Manager (for that location), User (for that location))
- [x] Location (Including: Manage Users) is accessible by (Institution Admin, Location-Manager (for that location))

**Tasks**
- [ ] Save locations/roles info to Vue Store and load locations left menu from Vue Store also.
- [ ] Restrict routes
- [ ] Remove UI links
- [ ] Review API permissions
