### ISSUE TITLE
BA Workplan - Carly

### ISSUE THREAD

**Issue by CarlyCotton** [bcgov/SIMS#3806]
# Work Priorities

## Pre EOY
**CAS (Supplier Maintenance)**
- [x] 	Connect to Test environment
- [x] 	Connect to UAT environments
- [x] 	Dashboard for Ministry Users
- [x] 	Manual Entry of Supplier/Site
- [x] 	Initial Search for Supplier
- [x] 	Create Supplier & Site
- [x] 	Search for existing site
- [x] 	Create Site
- [ ] 	Manual Intervention Report
- [x] 	Store Error Responses
- [ ] 	Error Report
- [ ] 	Error Handling - Retry
- [ ] 	Error Handling - Manual Resolve
- [ ] 	Update CAS/Site on Student Address Change
- [ ] 	UAT
- [ ] 	FRCR Doc
    - [ ] Workflows 
    - [ ] Guide doc?
- [ ] Connect to PROD?

## FT Release
**Assessment**
- [ ] 	CRA Data Being Used
- [ ] 	Change Request Data being Used
- [ ] 	Dependent/Independent Status
- [ ] 	Family Size
- [ ] 	Family Dependants 
- [ ] 	Parent Dependants
- [ ] 	Cost - Tuition/Fees/Exceptional
- [ ] 	Cost - MSOL
- [ ] 	Cost - Transportation
- [ ] 	Cost - Miscellanous
- [ ] 	Cost - Childcare
- [ ] 	Cost - Alimony/Support
- [ ] 	Cost - Second Residence
- [ ] 	Cost - Spousal Student Loan
- [ ] 	Cost - Books
- [ ] 	Contribution (Provincial) - Student
- [ ] 	Contribution (Federal) - Student
- [ ] 	Resources - Scholarships & Bursaries
- [ ] 	Resources - Targeted
- [ ] 	Contribution - Spouse 
- [ ] 	Contribution - Parent
- [ ] 	Need - Federal
- [ ] 	Need - Provincial
- [ ] 	Interface
- [ ] 	Eligibility
- [ ] 	PY Limits
- [ ] 	Maximum Award Values
- [ ] 	Award Configuration

**Application**
- [ ] Connect with Assessment Variables

**NOA**
- [ ] Connect with Assessment Variables

**Integration - NSLSC**
- [ ] FT Ecert still looks good post assessment updates
- [ ] FT Ecert includes overawards

**Integration - Bridge**
- [ ] SFAS to SIMS bridge still functioning
- [ ] SIMS to SFAS communications / layout maintenance

**Aviation Programs**
- [ ] Does it need to have limits within the assessment vs offering limits 

**FT Business Process Documentation**
- [ ] Create BP Document for FT Assessment

**CAS (AP Invoicing/T4A)**
- [ ] 	Connect to Test / UAT environments
- [ ] 	Dashboard for Ministry Users (All T4A-able disbursements)
- [ ] 	Approval Function to Send
- [ ] 	Error Handling - No Supplier/Site
- [ ] 	Error Handling - Retry
- [ ] 	Error Handling - Manual Resolve
- [ ] 	UAT / FRCR?
- [ ] 	Connect to PROD
- [ ] 	Provide student their T4A

**IER 12 / ECE**
- [ ] Update IER12 fields with new variables
- [ ] Engage PSIs?

**Report Updates**
- [ ] Update Ministry reports to include correct FT variables
- [ ] Update Institution reports to include correct FT variables

**CSG Stacking For FT??**
- [ ] Figure out stacking??

**Shelter Allowance??**
- [ ] Implement unknown new shelter allowance rules??
