### ISSUE TITLE
BA Workplan - Josh

### ISSUE THREAD

**Issue by Joshua-Lakusta** [bcgov/SIMS#3808]
Joshua Work Plan for full time

## Change Request Update project

- [x] Validate if something has changed during edit
- [ ] Use validation information to modify repeat processes 
     - don't retrigger exceptions if not changed
     - don't retrigger partner declaration if partner questions not touched
     - don't retrigger parent declaration if parent questions not changed
 
- [ ] Create new ui section to store new version of change requests
- [ ] create change request path which is edit post coe
- [ ] create change summary tab at the end of change request edit

## Restrictions

- [ ] Full time scholastic standing
- [ ] Aviation lifetime max
          - Analyze proper behavior of lifetime limit
          - Analyze how to detect these offerings and apply it

## Appeals

- [ ] Re label the current change request section to appeals
- [ ] Create customized Step parent waiver appeal

## Student changes school X5

- [ ]  create x5 process (cross over with NPWD)

## Exception request view

- [ ] Way for ministry users to be attached or take ownership of the work in the list
- [ ] More ability to filter or change the view in the exceptions section (allow for filtering based on type of exceptions attached)

## Verification

- [ ] Analysis to start (need to set what is needed for mvp of full time as a lot of promises have gone around with this item)

## Testing 

- [ ] support test design and management
