### ISSUE TITLE
Niño's Work Plan - Full-Time Integrations 

### ISSUE THREAD

**Issue by ninosamson** [bcgov/SIMS#3810]
**As a SIMS team, we have several integrations for the Full-Time release that require partner engagement, onboarding and approval to connect in production environments.**

The following files/integrations require coordination to support onboarding, testing, and approval.

# CAS
- [x] UAT in Train environment
- [x] FRCR approved 
- [ ] Approval from Finance to connect to production

# SIMS to SFAS
- [x] Testing of bridge file in DEV, TEST
- [x] Confirmation of processing of SIMS file in SFAS 
- [x] Backload of PROD files to SFAS 
- [x] Delta files working as expected 

# BC Publics 
- [ ] Engagement with Banner contacts regarding approach for any testing required 
- [ ] Development of test cases 
- [ ] Review integration with publics 

# NSLSC 
- [ ] Engagement to review files related to FT 
- [ ] Testing with Finastra 

# ATBC 

# SDPR 
- [x] Engagement to explain functionality in SIMS 
- [x] Design of API solution to pull SIMS clients by SIN
