### ISSUE TITLE
BA Workplan - Jer

### ISSUE THREAD

**Issue by JerPearson** [bcgov/SIMS#3826]
Jer's FT Work Plan

## FT App Review ##

- [x] Review missing questions 
- [ ] Analyze and remove redundant questions 
- [ ] Ensure question logic is correct
- [ ] Content review 

## FT Residency ##

- [x]  Reorganize questions to ensure group status is being applied correctly 
- [x]  Add dynamic questions
- [ ]  Create residency exception path for parents

## Dependant Info ##

- [x] Update family information tab to be dynamic
- [x] Rename to "Dependant Info"
- [x] Move all dependant question to this tab
- [x] Review relevant change requests to ensure accuracy 
- [x] Update sole custody question to ensure compliance 

## Parent info ##

- [ ] Add missing question to self report 
- [ ] Solution how to identify how many parents need to report
-

## Withdrawal Reversal ##

- [ ] Work and tasks TBD

## View Assessment ##

- [ ] Update NOA to reflect FT
- [ ] Update assessment page 
- [ ] Review overawards/maximums/restrictions 

## File Uploader ##

- [ ] View uploads in new folder
- [ ] Scope of work TBD
