### ISSUE TITLE
API modifications - Verify Existing Institution On institution login

### ISSUE THREAD

**Issue by mzmichellesmith** [bcgov/SIMS#395]
**Task 1:**

When an institution exists and a new institution user authenticates before they are added to the institution
User=New
Institution=Exists
- [x] New user logging into an institution (before being added by their admin) should be redirected back to the login saying that you have not been added

**Task 2:**
When an institution exists and a new institution user authenticates before they are added to the institution
User=New
Institution=New
- [x] New user and new institution logging in should be directed to complete institution account profile and created as an institution account admin after the account is created

**Task 3:**
- [x] Review/Remove Duplicate "check user" on files AuthService.ts and AppInstitution.vue, as shown below.

![image.png](https://images.zenhubusercontent.com/5fcebe3c076e6aaed83693fb/1eaf2fe3-51ef-46b3-80f1-6097299965db)

![image.png](https://images.zenhubusercontent.com/5fcebe3c076e6aaed83693fb/3e1d20bf-94aa-46fb-a72e-73ecc9eb5228)
