### ISSUE TITLE
Student: Content: Revise Action Required Tracker Card

### ISSUE THREAD

**Issue by JerPearson** [bcgov/SIMS#4059]
As a student I want a tracker card displayed when when my assessment is ready.

**Acceptance Criteria**
### Action Required Banner Update
- [ ] Add a button to the following tracker card that links to the most recent assessment that requires accepting of the assessment and takes them to the accept assessment page. (NOA_Approval_Status=required)

- [ ] Revise banner text to the following, but keep the header:
> Your assessment is ready.  You must view and accept your assessment by clicking "View assessment" below.  Please note that you may not be able to accept your assessment if you have a restriction, your Master Student Financial Assistance Agreement (MSFAA) is not signed, or further action is required on your application.   **View assessment button**

**Technical ACs:**

- [ ] `Assessment.vue` (Link: https://github.com/bcgov/SIMS/blob/d766304fa2d325dd18d9c5f4160113bd299003cf/sources/packages/web/src/components/common/applicationTracker/Assessment.vue#L13) needs to be updated with the above mentioned banner content. 
- [ ] Use the `actions slot` provided in the `ApplicationStatusTrackerBanner` component to add the button to the progress bar. Link: (https://github.com/bcgov/SIMS/blob/9a85a68040183d1364ff071839fb019772db4a32/sources/packages/web/src/components/common/applicationTracker/generic/ApplicationStatusTrackerBanner.vue#L29)

<img width="1436" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBK2dpQ0E9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--fc784138fb9b7a0bc3176fc61a528e58634287cc/image.png" alt="image.png" />

**Additional Context**
 - Ministry staff are taking calls from students from students asking why the "Accept Assessment" is greyed out.  Ministry staff are viewing the tracker cards screen noting there are no issues, when in fact the MSFAA isn't signed.  This is creating a high volume of phone inquiries and confusion.

**Comment by Joshua-Lakusta** [comment]
Please update to content change ticket for current accept assessment tracker @JerPearson
