### ISSUE TITLE
Institution User Provides Education Program Offering Information

### ISSUE THREAD

**Issue by mzmichellesmith** [bcgov/SIMS#421]
**As a** *(Institution)* **I want** *(provide information on my education program offering)* **So That** *(Student can Apply for that offering)*

**Additional Context**
Education Programs are broken into 2 components
**Education Program**: Often referred to as the "tombstone information". This is the root information that will be approved by the ministry. Students will need to select their program before looking at their offering. Information in this component will be applicable to ALL offerings. Education programs are located at the institution account entity level and will be able to be used at any location
**Education Program Offering**: This is the component that details the specifics about an actual offering of that program. This will contain the specifics about an offering. Offerings are always specific to a location

**Acceptance Criteria**
Given (an Institution User), When (entering the information on a program's first offering ), Then (they have to complete the following questions for one Education Program: 

**Study Dates**
The User must provide a start and end date OR select "no program dates (for continuous entry)"
-[  ] Start Date _(Calendar Standard)_
-[ ]  End Date  _(Calendar Standard)_ Must be later than the start date and no less than 6 weeks later or longer than 52 weeks.
-[ ]  "no program dates (for continuous entry)" _(radio button)_ If this button is selected disable the fields below and display the following message "TBD something something"

**Study Breaks** (Optional)
-[  ] Provide the following text: "Identify the scheduled breaks that are planned for the program year (Aug 1 to July 31). Breaks should not exceed two weeks, except for the calendar year-end break (December to January) which can be three weeks long. Do not include breaks that are prior to or after the study period."
-[  ] Start Date _(Calendar Standard)_ 
-[ ]  End Date  _(Calendar Standard)_ Must be later than the start date

**Study Costs**
- [x]  "No Fixed Cost" _(Radio Button)_ If this button is selected then disable the fields in this section below.
- [x]  Actual Tuition _(Free Text numbers )_
- [x]  Mandatory Fees _(Free Text numbers )_
- [x]  Program Related Costs _(Free Text numbers)_
- [x]  Exceptional Costs _(Free Text numbers)_

**Tuition Remittance**
- [x] "Is tuition remittance requested?" _(Radio Button)_ If this button is selected provide the following field below
     - [x] "Amount Requested" _(Free Text numbers)_

**Study Delivery**
- [x]  "How will this offering be delivered"? Provide the following options: _(Validation back to the program information the options are:)_
     - [x] Onsite
     - [x] Online
     - [x] Blended

**Final Steps**
- [x] Given (An Institution User), When (selects save), Then (the program offering information is saved all fields mandatory fields are saved)

**tasks**
-Create DB Migration from #353
-Create form.io form
-Render form
-Submit to SIMSDB

Figma: https://www.figma.com/file/VykmBDwobGoGvK9M5wgOvN/StudentAid-BC-App-Design-System-(WIP!!)---FreshWorks-Studios?node-id=1884%3A21118
