### ISSUE TITLE
Institution User Declines Program Information Request

### ISSUE THREAD

**Issue by roopfw** [bcgov/SIMS#428]
*As an (Institution User) I want (to Declines Program Information Request) So That ( I only confirm students who have applied to my School)

**Additional context**
-  Sometimes an institution cannot complete a PIR for a student for specific reasons. EG. the student has not yet applied to that specific school. 

**Acceptance Criteria**
- [x] On click of "view" on the program information request summary screen for a required application show the PIR form (already built)
- [x] Under "Institution Entered Details" add a checkbox "Deny Program Information Request"
- [x] Deny Program Information Request = True :Hide Program and Offering details and display the denied reasons

"On Decline' Reasons-Options to choose from include:
- [x] School is unable to confirm student identity, please confirm your student number or contact Financial Student Aid Office for more information
- [x] Study period dates selected are incorrect, please submit an application for each semester individually
- [x] Programs you are registered in is not eligible for Student Aid BC funding, please contact Financial Aid Office for more information
- [x] Our records indicate you are not registered, please re-submit application after registration
- [x] Study period dates are incorrect, please contact Financial Aid Office for more information
- [x] Other
- [x] On "Other" display text area (500 character max length) (Required)

**Tasks**
- [x] Use a form for denied reasons
- [x] On "Deny Enrolment" update pir_status to "Declined"
- [x] Migration for pir_denied_id column
- [x] Migration for pir_denied_reason table (id and reason)
