### ISSUE TITLE
Institution User Views and edits Education Program Information details

### ISSUE THREAD

**Issue by mzmichellesmith** [bcgov/SIMS#470]
**As a** *(Institution location)* **I want** *(view and edit information on my education program)* **So That** *(I can maintain my program information)*

**Additional Context**
See #279 for add program
This uses the same form as "Add Program"

**Acceptance Criteria**
- [x] Given (an Institution User), When (selecting edit program), Then (they have the ability to view and edit all program information)
- [x] Given (an Institution User), When (entering program information), Then (they have to complete all mandatory fields)
- [x] Given (An Institution User), When (selects submit), Then (the program information is saved)
- [x] All fields are mandatory

**Tasks**
- [ ] Render form
- [ ] Submit to SIMSDB and formio for new application

Figma: https://www.figma.com/file/VykmBDwobGoGvK9M5wgOvN/StudentAid-BC-App-Design-System-(WIP!!)---FreshWorks-Studios?node-id=1884%3A20472
