### ISSUE TITLE
Institution User Views and edits Education offering details

### ISSUE THREAD

**Issue by abschwenker** [bcgov/SIMS#471]
**As a** *(Institution location)* **I want** *(view and edit information on my education program offering)* **So That** *(I can maintain my program offering information)*

**Additional Context**
See #421 for add offering
This uses the same form as "Add Program"

**Acceptance Criteria**
- [x] Given (an Institution User), When (selecting edit offering), Then (they have the ability to view and edit all offering information)
- [x] Given (an Institution User), When (entering offering information), Then (they have to complete all mandatory fields)
- [x] Given (An Institution User), When (selects submit), Then (the offering information is saved)
- [x] All fields are mandatory

**Tasks**
- [x] Render form
- [x] Submit to SIMSDB

Figma: https://www.figma.com/file/VykmBDwobGoGvK9M5wgOvN/StudentAid-BC-App-Design-System-(WIP!!)---FreshWorks-Studios?node-id=1884%3A21118
