### ISSUE TITLE
Workflow approach fix's

### ISSUE THREAD

**Issue by michesmi** [bcgov/SIMS#555]
**Additional Context**
Change workflows so SIMSDB is source of truth for status's. 

**Tasks**
- [x] Change Camunda to not call API to update status. Make API update status directly to SIMSDB (COE, PIR)
- [x] Change Assessment-Gateway workflow to update ProcessID (SIMSDB column) from Camunda. If workflowID is set, throw exception.
- [x] Camunda calls from simsapi should "fail quietly". (Application Submission, COE, PIR)
