### ISSUE TITLE
UI/UX Application Details Page

### ISSUE THREAD

**Issue by abschwenker** [bcgov/SIMS#599]
**Tasks**
- [ ] Review application status's (Andrew Schwenker to provide guidance)
- [ ] Review application status nav bar
- [ ] Review Notifications/messaging on application details page

**Acceptance Criteria**
- [ ] Provide Completed wireframes with all applicable status
- [ ] Provide Completed wireframes with all application status and messages
