### ISSUE TITLE
Active Applications Summary Page 

### ISSUE THREAD

**Issue by michesmi** [bcgov/SIMS#652]
As a (institution user) I want (see a summary page of "active applications") So That (I can report a change to a students scholastic standing)

**Additional Info**
- This is Similar to the COE and PIR Summary Pages but this one lists all active applications (After the Student has been Confirmed for Enrolment..

**Tasks**
- [x] Create "Active Applications" summary page with identical columns to PIR and COE
Name | Study Period | Application # | Status
- [x] Status will be based off application_status 'complete'
- [x] View button change to "VIEW" which renders form "Institution Report Student Change" in "#335     (form path: reportachange)
