### ISSUE TITLE
Add institution Code on Institution Location

### ISSUE THREAD

**Issue by michesmi** [bcgov/SIMS#664]
**Describe the task**
- We Include this is the files we send and receive with CSFA and is used as an identifier for an institution

**Acceptance Criteria**
- [x] 4 Upper Case Letters free field on the institution location page
- [x]  This is a required field- (going to be nullable in the database.
- [x] Institution Locations can share the same code.

**Tasks**
- [x] Migration to add column institution_code    (nullable)
- [x] Add field on form
- [x] Add to API to save/retrieve
- [x] Manage Institution -> Location Summary -> Add&Edit should use the form "Institution Location"
