### ISSUE TITLE
Determine Workflow Approach

### ISSUE THREAD

**Issue by michesmi** [bcgov/SIMS#685]
**Tasks**
2- 1hour Sessions to determine the overall approach for camunda workflow below
- [x] Determine how to "exit workflow" (decline PIR and decline COE for example) (Not needed since decision it to cancel workflow)
- [x] Determine how to handle failed calls (camunda calls - #593, simsapi, #555)
- [x] Determine calling the workflow directly ("try" to call camunda via #555 with DB as source of truth, scheduler to be created when needed)
- [x] Create output technical debt tickets #555, #715
1. Add retry to Camunda Calls (#593)
2. Add SIMSAPI retry to call Camunda (#593)

**Session 1 notes:**
-Add payload queue, db messages
create generic table to handle transactions to camunda. Save payload. Create thing to resend calls
change camunda to save workflow id

- Create schedulers to "unstick" applications
Application Submit
PIR - submit
assessment - submit
COE - submit
