### ISSUE TITLE
Create common component for student application

### ISSUE THREAD

**Issue by michesmi** [bcgov/SIMS#695]
**Tasks**

- [x] Create a common "student application" component to be shared among Student and Ministry
- [x] currently approved program are only listing in the drop down, this logic is for only required while editing or creating an application , when a user is viewing an application, the program or offering value should considered irrespective of the status, (currently, only approved programs are only considered) (for reference -> https://github.com/bcgov/SIMS/pull/1032/commits/53de671d53432fd2a26924a42e7f9258f96638e4, the API and dropdown id fixes in this commit is reverted due to code duplication, but we need to implement something similar in this story)
- [x] Add an html component instead of dropdown an display the values, without fetching all programs or offering from DB
- [x] Create interface for dynamic data application that is manipulated by API (make a comment to be clear that it is a partial mapping)
- [x] Before returning dynamic data, set null to make dropdown null

**Acceptance Criteria**
- [x] Student Drop downs (when able to select) always have "approved programs"
- [x] Student Drop downs (when able to select) always have "designated locations"
- A designated institution location is 1 that is:
The location record is approved and it belongs to the 
- [x] Students returning to a "draft application" or "edit application" should display a blank dropdown if the programs are "not approved"
- [x] Students returning to a "draft application" or "edit application" should display a blank dropdown if the locations are "not approved"
- [x] Students returning to a declined/completed application (any read-only state) return the program regardless of the state of the program status (return the label)
- [x] Students returning to a declined/completed application (any read-only state) return the institution location regardless of the state of the designation status (return the label)
- [x] Any time a read-only form is shown, do NOT show dropdowns, display a HTML component with the label
- [x] Ministry functionality follows the same as above points. When read-only display labels
- [x] API for aest is passing application and student id-> refactor the api
- [x] updated application controllers as per new Router POC
- [x] api tags?
