### ISSUE TITLE
Student Welcome Page 

### ISSUE THREAD

**Issue by michesmi** [bcgov/SIMS#730]
**As a** *Student* **I want** to land on a welcome page* * **So That** *I can feel welcome, view any important upcoming news and navigate using the to nav bar to the section I need to apply for Financial Aid, View my profile, see my messages, etc.

**MVP Dashboard is:**

- [x] A Welcome Message 
(big text) Welcome to StudentAid BC
(Normal text) We are excited to assist you on your Financial Aid Journey to Post-Secondary Education" Please use the navigation bar at the top right to get started." 
- [x] "A picture of a smiling Student" (TBD)
- [x] "Capability to provide Message Board Banner"
 General SABC news (to all students). Information about Upcoming programs, applications dates, new system enhancements could be updated here by staff
- [x] Make it a bit pretty

**Tasks**
- [x] Use a Form.io form for Content. Form Name:"Student Dashboard"
