### ISSUE TITLE
Institution Welcome Page

### ISSUE THREAD

**Issue by michesmi** [bcgov/SIMS#731]
**MVP Dashboard is:**

- [x] A Welcome Message 
(big text) Welcome to StudentAid BC
(Normal text) "We are excited to assist you in supporting Students on the Post Secondary Education Journey"

- [ ] "A picture of a smiling Student"

- [ ] "Capability to provide Message Board Banner"
 General SABC news (to all students). Upcoming programs, applications dates, new system enhancements. 

**Tasks**
- [ ] Use a Form.io form for Content. Form Name:"Institution Dashboard"
