### ISSUE TITLE
Restrictions Review

### ISSUE THREAD

**Issue by michesmi** [bcgov/SIMS#736]
**Tasks**
2- 1hour sessions to review Restrictions and design a build approach
- [x] 1st session Roop to lead first 30min on Restrictions research and what they mean
- [x] 2nd session design and develop build approach to be implemented - Completed in grooming. Draft attached to #752. Developer to verify and review with team once tasked
**Acceptance criteria**
- [x] Create output development ticket --#752
