### ISSUE TITLE
Schedule Student Disbursement

### ISSUE THREAD

**Issue by michesmi** [bcgov/SIMS#753]
Additional Context
- On the NOA we display to the student when they are receiving funds
- These funds need to be calculated after the award is determined but displayed on the NOA
- These funds calculated to either have 1 disbursement amount or 2 based off the workflow attached
- Once scheduled a job will pick up these disbursements with dates to be disbursed
CSL(Canada Student loan)
CSG (Canada Student grant)
BCSL(BC Student loan)
BCSG (BC Student Grant)

**Acceptance Criteria**
- [ ] Add sub process in Camunda  for scheduling disbursements per workflow
- [x] Create DB structure (verify naming conventions)
**REVISIONS BELOW IN COMMENTS**
![image.png](https://images.zenhubusercontent.com/5fce9c77aab275719112dc74/b1e68a51-f2a7-4da6-b30d-a5d26a1bd920)

**updates**
latest workflow - [https://app.zenhub.com/files/319429847/be430ad6-e773-45be-9b11-bfc70473ce71/download](https://app.zenhub.com/files/319429847/be430ad6-e773-45be-9b11-bfc70473ce71/download)

**Tasks**
- Create DB structure per attached, (verify naming conventions)
- Add after award calculation in camunda a process for creating a schedule and applicable grants (according to workflow)

**Rules**
- [ ] If either disbursement schedule is NULL when 2 are determined, only create 1 disbursement date (all upfront)

DRAFT Disbursement Model  (Oct 6, 2021) Updates OTW
[https://app.zenhub.com/files/319429847/a947d143-c960-4700-bee9-207a292f44f0/download](https://app.zenhub.com/files/319429847/a947d143-c960-4700-bee9-207a292f44f0/download)

**Comment by abschwenker** [comment]
![image.png](https://images.zenhubusercontent.com/5fce9c77aab275719112dc74/bb4760b5-5b08-4831-8625-e1900204b74d)
