### ISSUE TITLE
4.1.1 Ministry-Login and Manage Account (Profile- Communicate- Banner Message)

### ISSUE THREAD

**Issue by michesmi** [bcgov/SIMS#841]
- [ ] Ministry Login 
-A ministry user can login and logff
- [ ] Ministry user Welcome Page
- A ministry user can view their welcome page
- [ ] Ministry user navigation
- A ministry user can navigate in their portals
- [ ] Ministry can add system announcement banners to login portals & welcome/home page for users.
    - _As a Ministry user, I need to be able to publish banners on the various SIMS sites for different users, to notify about system changes or outages. These can be shown prior to users being authenticated on the login pages for Supporting Users, Students, and Institutions. They can also be shown to authenticated users after login: Institutions, Ministry, Students (not Supporting users). This announcement will be on the page on login (Home), it is not dismissible, but does not follow the user as they navigate. There can be multiple announcements within the same banner for each portal._

---
### Announcements
<img width="894" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBd0NoQkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--19f57bbb85ebe656fdc905fb0e1f0fa6b95ac595/image.png" alt="image.png" />
<img width="895" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBd3loQkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--3cdfbe8fc4271d94a1d220b98c3f4c50ec52b6b3/image.png" alt="image.png" />
<img width="790" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBeENoQkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--14f0339938b6bafaf0d42bed9c0e0074e8199f71/image.png" alt="image.png" />
<img width="466" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBdzZoQkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--654f3db6c15a17fc35de17404187e37671bc00cf/image.png" alt="image.png" />
