### ISSUE TITLE
Ministry User Views Student Restrictions

### ISSUE THREAD

**Issue by michesmi** [bcgov/SIMS#878]
*Restrictions also exist for Institutions

**As a** *(Ministry User )*
**I want** *(View a Students account)*
**So That** *(I can look up information related to that Student)*

Master Story (#771) 

### Prototype
https://www.figma.com/file/VykmBDwobGoGvK9M5wgOvN/StudentAid-BC-App-Design-System---FreshWorks-Studios?node-id=5246%3A41267

### Additional Context
- UX Ticket #796
- Once a Student account is successfully created, then it can be viewed by approved ministry users
- A ministry user will be able to see the details of a Student Account. This will include profile information, Application(s), Restrictions, and Notes
![image.png](https://images.zenhubusercontent.com/60c7d7040a42d68fb4abaa59/35b11271-1e6a-4670-93bd-638cbb45bb73)

### Acceptance Criteria
- [ ] From the 'Find Student Page', The ministry user searches and selects for the Studentthey wish to view and they are directed to the Student Details Page- US #91

**Restrictions**
![image.png](https://images.zenhubusercontent.com/60c7d7040a42d68fb4abaa59/04142abc-5294-4bba-8ce2-249da03eb5d6)
- [ ] The Ministry User can view All Restrictions associated with that Student ( Type, Reason, Added, Resolved and Status)
- [ ] The user can sort on each field 
- [ ] The user can see 10 items in the table. 
- [ ] Type ( Federal or Provincial Restriction)
- [ ] Reason (A truncated version of the reason (500 characters0
- [ ] Added ( The date the restriction was added ( Month, day, year)
- [ ] Resolved (The date the restriction was resolved  ( Month, day, year)- If not resolved indicate with a (dash) 
- [ ] Status (Status of the restriction- Active or Resolved)
- [ ] View- Showes the Restriction in more detail and they can resolve the restriction here- (US is  #846)
- [ ] Ministry User can "Add Restriction" (US is #846)
