### ISSUE TITLE
Student Restriction updates

### ISSUE THREAD

**Issue by michesmi** [bcgov/SIMS#948]
**- Additional Context**
- Update db to support individual message types and actions for each restriction
- break the PR (db changes in 1)
- Sharepoint General->Analysis->Restrictions
- If we have extra type=federal restrictions, keep them in DB

**- Acceptance Criteria**
**Restriction DB Changes**
- [x] remove explicit primary key, use SERIAL (not integer)
- [x] remove "allowed_count" column (add todo to existing logic, where this field is used)
- [x] Add action_type ENUM with (No effect, Stop full time BC funding, Stop part time apply, Stop full time apply, Stop part time disbursement, Stop full time disbursement)  Use array of ENUM
- [x] Add notification_type ENUM with (No effect, Warning, Error)
- [x] update update restriction initial data.

**Restrict Actions**
- [x] When action_type = No effect, take no action
- [x] When action_type = Stop part time apply, disable submission of part time applications (On submit only , save draft is not submission). On Click of submit display toast message "Active restriction!" "You have a restriction on your account"
- [x] When action_type = Stop full time apply, disable submission of full time applications (On submit only , save draft is not submission). On Click of submit display toast message "Active restriction!" "You have a restriction on your account"
- [ ] When action_type = Stop part time disbursement, stop part time funding from being disbursed (Ticket #1197)
- [ ] When action_type = Stop full time disbursement, stop full time funding from being disbursed (Ticket #1197)
- [ ] When action_type = Stop full time BC funding, stop bcsl funding from being disbursed (Ticket #1197)

**Comment by SaurabhA-CGI** [comment]
Closed by mistake. Was trying to get back to the EPIC. Reopened.

**Comment by abschwenker** [comment]
AC update to accommodate a cleaner implementation, previous AC here for reference only![image.png](https://images.zenhubusercontent.com/5fce9c77aab275719112dc74/fcdf50c9-c157-4037-b205-6ac1f9c9bed6)
